mcc68k -c -nKc m_main.c
mcc68k -c -nKc sio_int.i
mcc68k -c -nKc sm_int.i
mcc68k -c -nKc sio_init.i
mcc68k -c -nKc getsio.i
mcc68k -c -nKc gethost.i
mcc68k -c -nKc chkhost.i
mcc68k -c -nKc chksio.i
mcc68k -c -nKc lfproc.i
mcc68k -c -nKc send_img.i
mcc68k -c -nKc adj_err.i
mcc68k -c -nKc rolproc.i
mcc68k -c -nKc sendbuff.i
mcc68k -c -nKc sendslv.i
mcc68k -c -nKc clrstimg.i
mcc68k -c -nKc tostimg.i
mcc68k -c -nKc copyimg.i
mcc68k -c -nKc loadtb.i
mcc68k -c -nKc htdbtb.i
mcc68k -c -nKc vtdbtb.i
mcc68k -c -nKc htcdtb.i
mcc68k -c -nKc htvtdbtb.i
mcc68k -c -nKc rvmem.i
mcc68k -c -nKc sdmem.i
mcc68k -c -nKc ulmem.i
mcc68k -c -nKc bfmem.i
mcc68k -c -nKc makekor.i
mcc68k -c -nKc makeeng.i
mcc68k -c -nKc emul.i
mcc68k -c -nKc ctrproc.i
mcc68k -c -nKc escproc.i
mcc68k -c -nKc autoclr.i
mcc68k -c -nKc selftest.i
mcc68k -c -nKc institem.i
mcc68k -c -nKc m_init.i
mcc68k -c -nKc saveatt.i
mcc68k -c -nKc setatt.i
mcc68k -c -nKc loadatt.i
mcc68k -c -nKc selfslv.i
mcc68k -c -nKc getpio.i
mcc68k -c -nKc chkpio.i
mcc68k -c -nKc conprn.i
link master
