	.LIST	OFF
;********************************************************
;							*
;	M4324 ALARM ERROR CODE DEFINITION		*
;							*
;	FILE NAME	ALARM.H				*
;	CREATED		24/OCT/1990			*
;							*
;********************************************************
;
;	ALARM ERROR CODE
;
ZERAM:	.EQU	129		; RAM ERROR
ZEROM:	.EQU	130		; ROM ERROR
ZEEEU:	.EQU	131		; EEPROM USER AREA ERROR
ZEEEP:	.EQU	132		; EEPROM ERROR
ZECG:	.EQU	133		; CG ROM ERROR
ZEPRG:	.EQU	134		; PROGRAM ERROR
ZEINT:	.EQU	ZEPRG+H'0100	; INTERRUPT ERROR
ZESLV:	.EQU	135		; SLAVE CPU RUN STATUS ERROR
ZESL1:	.EQU	ZESLV+H'0100	; SLAVE CPU TRSREQ ERROR
ZESL2:	.EQU	ZESLV+H'0200	; SLAVE CPU TRANSMIT TIME OUT
ZESL3:	.EQU	ZESLV+H'0300	; SLAVE CPU STATUS TIME OUT
ZESL4:	.EQU	ZESLV+H'0400	; SLAVE CPU STATUS ADDRESS ERROR
ZEDRV:	.EQU	136		; CR/LF MOTOR DRIVER ERROR
ZETR:	.EQU	137		; STEP MOTOR DRIVER ERROR
ZEHD:	.EQU	138		; HEAD DRIVER ERROR
ZEEC:	.EQU	139		; CR ENCODER ERROR
ZEFRM:	.EQU	140		; FRAME WIDTH ERROR
ZESPD:	.EQU	141		; CR SPEED ERROR
ZEFAN:	.EQU	142		; COOLING FAN ERROR
ZERBW:	.EQU	143		; RIBBON WIND MOTOR ERROR
ZELVR:	.EQU	144		; LEVER CHANGE MOTOR ERROR
ZERBS:	.EQU	145		; RIBBON SHIFT MOTOR ERROR
ZEHDS:	.EQU	146		; HEAD SHIFT MOTOR ERROR
ZEPWR:	.EQU	147		; POWER SUPLY OVER HEAT ERROR
ZEHDT:	.EQU	148		; HEAD THERMAL ERROR
ZEPIF:	.EQU	149		; NO PARALLEL I/F BORAD
;
;	ALARM ERROR MACRO
;
	.MACRO	SETALM	C
\;	.AIF	"\C" EQ "R0"
\;	TRAPA	#14
\;	.EXITM
\;	.AENDI
	MOV.B	\C,R0
	TRAPA	#14
	.ENDM
	.LIST	ON
