	.LIST	OFF
;********************************************************
;							*
;	M4324 AX COMMON OWN BUFFER DEFINITION		*
;							*
;	FILE NAME	AX_BUF.H			*
;	CREATED 	23/OCT/1990			*
;							*
;********************************************************
;
;	<< COMMON BUFFER DEFINE >>
;
	.IMPORT 	DLDBF	; DOWNLOAD BUFFER
	.IMPORT 	DLRBF	; DOWNLOAD / GAIJI RECEIVE BUFFER
	.IMPORT 	DLDID	; DOWNLOAD ID
	.IMPORT 	EDBF1	; EDIT BUFFER 1 START POINTER
	.IMPORT 	EDBF2	; EDIT BUFFER 2 START POINTER
	.IMPORT 	GIJBF	; GAIJI    BUFFER
	.IMPORT 	HTBF	; HORIZONTAL TAB START POINTER
	.IMPORT 	IMGBF	; IMAGE BUFFER START POINTER
	.IMPORT 	TXTBF	; TEXT	BUFFER START POINTER
	.IMPORT 	TXTBE	; TEXT	BUFFER END   POINTER
;
	.IMPORT 	LOWC, MIDC, HIGHC			;\ 920309
	.IMPORT 	HBUF20	; 20 Byte working space free	;\ 920320
;			0	; ESC + A Value save
;			1	;HG START DELEMETER
;			2	;HG STOP  DELEMETER
;
	.LIST	ON
