	.LIST	OFF
	.SECTION	DP2RAM,DUMMY,LOCATE=H'FE40
;********************************************************
;							*
;	M4324 WORK AREA DEFINITION			*
;							*
;	FILE NAME	AX_DP2.H			*
;	CREATED 	08/MAR/1991			*
;							*
;********************************************************
;
;	<< FUNCTION CODE DEFINE >>
;
ZBEL:	.EQU	  7		; BELL
ZBS:	.EQU	  8		; BS
ZHT:	.EQU	  9		; HT
ZLF:	.EQU	 10		; LF
ZVT:	.EQU	 11		; VT
ZFF:	.EQU	 12		; FF
ZCR:	.EQU	 13		; CR
ZSO:	.EQU	 14		; SO
ZSI:	.EQU	 15		; SI
ZDC1:	.EQU	 17		; DC1
ZDC2:	.EQU	 18		; DC2
ZDC3:	.EQU	 19		; DC3
ZDC4:	.EQU	 20		; DC4
ZCAN:	.EQU	 24		; CAN
ZEM:	.EQU	 25		; EM
ZSP:	.EQU	 32		; SPACE
ZDEL:	.EQU	127		; DELETE
;
;	<< MISCELLANEOUS CONSTANT >>
;
ZCLMUL: .EQU	 12		; COLUMN MULTIPLIER (1/120 inch x n)
ZFLCLM: .EQU	ZCLMUL*12*136	; FULL COLUMN (13.6 inch)
;
;	<< CHARACTER COLUMN >>
;
ZCLPIC: .EQU	ZCLMUL*12	; PICA		 COLUMN
ZCLELT: .EQU	ZCLPIC*10/12	; ELITE 	 COLUMN
ZCLPCN: .EQU	ZCLPIC/2	; PICA	CONDENSE COLUMN 	;920326
ZCLECN: .EQU	  60		; ELITE CONDENSE COLUMN 	;62 -> 60 1020
ZCL15C: .EQU	ZCLPIC*2/3	; 15 CPI	 COLUMN
ZCL13M: .EQU	  108		; 13.3 CPI	 COLUMN 	;920401
;
;	<< KANJI CONSTANT >>
;
ZKCGCL: .EQU	 24		; KANJI CG COLUMN SIZE
ZHCGCL: .EQU	 11		; HALF	CG COLUMN SIZE
ZQCGCL: .EQU	 12		; QUARTER CG COLUMN SIZE
	;
ZFSPCD: .EQU	H'2121          ; FULL SPACE CODE
;
;	<< DOT COLUMN >>
;
ZCL60:	.EQU	ZCLPIC*10/60	;  1/ 60 INCH COLUMN
ZCL80:	.EQU	ZCLPIC*10/80	;  1/ 80 INCH COLUMN
ZCL90:	.EQU	ZCLPIC*10/90	;  1/ 90 INCH COLUMN
ZCL120: .EQU	ZCLPIC*10/120	;  1/120 INCH COLUMN
ZCL180: .EQU	ZCLPIC*10/180	;  1/180 INCH COLUMN
ZCL240: .EQU	ZCLPIC*10/240	;  1/240 INCH COLUMN
ZCL360: .EQU	ZCLPIC*10/360	;  1/360 INCH COLUMN
ZCLPRP: .EQU	ZCL360		; PROPORTIONAL COLUMN
;
;	<< COLOR POSITION >>
;
ZBLCKS: .EQU	  0		; BLACK   SELECT VALUE
ZCYANS: .EQU	  1		; CYAN	  SELECT VALUE
ZMGNTS: .EQU	  2		; MAGENTA SELECT VALUE
ZYLLWS: .EQU	  3		; YELLOW  SELECT VALUE
;
;	<< PRINT PITCH CONSTANT >>
;
ZPTC36: .EQU	  0		; 1/360 INCH
ZPTC24: .EQU	  1		; 1/240 INCH
ZPTC18: .EQU	  2		; 1/180 INCH
ZPTC12: .EQU	  3		; 1/120 INCH
;
;	<< PRINT SPEED CONSTANT >>
;
ZSPD10: .EQU	  0		; LOW	 SPEED
ZSPD15: .EQU	  1		; MIDDLE SPEED
ZSPD20: .EQU	  2		; HIGH	 SPEED
ZSPD30: .EQU	  3		; SUPER  SPEED
;
;	<< APPLICATION FLAG AREA >>
;
;	<< Note >>	xxxxF -> FLAG
;			xxxxS -> SAVE AREA
;			xxxxC -> COUNTER
;			xxxxP -> POINTER
;			+     -> TEXT BUFFER MODE FLAG BITS
;
PSPDFS: .RES.B	  1		; PRINT SPEED FLAG (1 LINE) SAVE AREA
;ZPS10: .EQU	  0		;     NATIVE PRINT SPEED
;ZPS15: .EQU	  1		;     x1.5 PRINT SPEED
;ZPS20: .EQU	  2		;     x2.0 PRINT SPEED
;ZPS30: .EQU	  3		;     x3.0 PRINT SPEED
;	.EQU	4->7		; << Free bit >>
;
;	<< M4324 AX APPLICATION FLAG AREA >>
;
APL0F:	.RES.B	  1		; APPLICATION 0 FLAG (CLEAR BY ESC+@,INIT/)
QGRPTB: .EQU	  0		; CHARACTER TABLE 0 (0 = KATAKANA / 1 = GRAPHIC)
QHTSTR: .EQU	  1		; HT SET SEQ. RECEIVE
QVTSTR: .EQU	  2		; VT SET SEQ. RECEIVE
QCDEX1: .EQU	  3		; SET HIGH CONTROL CODE VALID
QZEROS: .EQU	  4		; SLASH ZERO
QBBFFL: .EQU	  5		; BAR CODE BUFFER FULL
QPRTON: .EQU	  6		; PRINT ON-LINE
QIMGDT: .EQU	  7		; IMAGE DATA FLAG
	;
XGRPTB: .EQU	H'01            ;
XHTSTR: .EQU	H'02            ;
XVTSTR: .EQU	H'04            ;
XCDEX1: .EQU	H'08            ;
XZEROS: .EQU	H'10            ;
XBBFFL: .EQU	H'20            ;
XPRTON: .EQU	H'40            ;
XIMGDT: .EQU	H'80            ;
;
APL1F:	.RES.B	  1		; APPLICATION 1 FLAG (CLEAR BY ESC+@,INIT/)
;	.EQU	0->3		; << INTERNATIONAL CG SELECT >>
;	.EQU	4->5		; << Free bit >>
QFJSC3: .EQU	  6		; FULL JUSTIFY CONTROL FLAG 3 (EXIST RELATIVE COLUMN POSITION FOR REVERSE)
QIMG24: .EQU	  7		; GET IMAGE 24 PIN RECEIVE FLAG
	;
;	.EQU	H'01            ; *INTERNATIONAL CG SELECT
;	.EQU	H'02            ; *INTERNATIONAL CG SELECT
;	.EQU	H'04            ; *INTERNATIONAL CG SELECT
;	.EQU	H'08            ; *INTERNATIONAL CG SELECT
;	.EQU	H'10            ;
;	.EQU	H'20            ;
XFJSC3: .EQU	H'40            ;
XIMG24: .EQU	H'80            ;
;
XINTCG: .EQU	H'0F            ; INTERNATIONAL CG SELECT MASK
;
APL2F:	.RES.B	  1		; APPLICATION 2 FLAG (CLEAR BY ESC+@,INIT/)
QBSEQR: .EQU	  0		; BAR-CODE SEQUENCE DATA RECIVE FLAG
QPRTCR: .EQU	  1		; PRINT ON-LINE (CR/LF/VT/FF)
QIMGRV: .EQU	  2		; IMAGE DATA RECIVE FLAG
QSPDB:	.EQU	  3		; SPEED B MODE FLAG
QBUFFL: .EQU	  4		; BUFFER FULL FLAG
QKJHAC: .EQU	  5		; KANJI HALF ADJUST FLAG
QDELVL: .EQU	  6		; DELETE CODE VALID
QJSTPR: .EQU	  7		; JUSTIFICATION PRINT
	;
XBSEQR: .EQU	H'01            ;
XPRTCR: .EQU	H'02            ;
XIMGRV: .EQU	H'04            ;
XSPDB:	.EQU	H'08            ;
XBUFFL: .EQU	H'10            ;
XKJHAC: .EQU	H'20            ;
XDELVL: .EQU	H'40            ;
XJSTPR: .EQU	H'80            ;
;
UMOD00: .RES.B	  1		; 911223 DEFAULT LPI CONTROL
UMOD01: .RES.B	  1		; WORKING RAM 920128
;
QKCSWA: .EQU	  0		; 911127 (ANK/KANJI CHECK)
QKEIVP	.EQU	  1		; 920316 V & H connection
QKCSWC: .EQU	  2		; 911206 (OPTION B/D SEL)
QKCSWD: .EQU	  3		; 920207 (HANGUL COMBI/COMPO)
QKCSWE: .EQU	  4		; 920207 (NBYTE STATE)
QKCSWF: .EQU	  5		; 920219 (NBYTE시 한글 모드 CHECK)
QKCSWG: .EQU	  6		; 920328 (10 : 10 CPI IN KSC MODE)
QKCSWH: .EQU	  7		; 920401 (13.3 CPI CONTROL)
;
;	<< PRINT MODE FLAG AREA >>
;
PTMD0F: .RES.B	  1		; PRINT MODE 0 FLAG
QDLSEL: .EQU	  0		;+ DOWNLOAD MODE SELECT
QSUPSC: .EQU	  1		;+ SUPER SCRIPT
QSUBSC: .EQU	  2		;+ SUB	 SCRIPT
QOUTLN: .EQU	  3		;+ OUTLINE MODE
QSHADW: .EQU	  4		;+ SHADOW MODE
QVENLR: .EQU	  5		;+ VERTICAL ENLARGE MODE
QHENLR: .EQU	  6		;+ HORIZONTAL ENLARGE MODE
QENL1L: .EQU	  7		; HORIZONTAL ENLARGE 1 LINE
	;
XDLSEL: .EQU	H'01            ;
XSUPSC: .EQU	H'02            ;
XSUBSC: .EQU	H'04            ;
XOUTLN: .EQU	H'08            ;
XSHADW: .EQU	H'10            ;
XVENLR: .EQU	H'20            ;
XHENLR: .EQU	H'40            ;
XENL1L: .EQU	H'80            ;
	;
XSTLMK: .EQU	XOUTLN+XSHADW	; CHARACTER STYLE MASK
;
PTMD1F: .RES.B	  1		; PRINT MODE 1 FLAG
QELITE: .EQU	  0		;+ *ELITE MODE
QPROPO: .EQU	  1		;+ *PROPORTIONAL MODE
QCONDE: .EQU	  2		;+ *CONDENSE MODE
QEMPHA: .EQU	  3		;+ *EMPHASIZE MODE
QDBSTR: .EQU	  4		; *DOUBLE STRIKE MODE
QPIT15: .EQU	  5		;+ 15 CPI
QITALC: .EQU	  6		;+ *ITALIC MODE
QUNDLN: .EQU	  7		;+ *UNDERLINE MODE
	;
XELITE: .EQU	H'01            ;
XPROPO: .EQU	H'02            ;
XCONDE: .EQU	H'04            ;
XEMPHA: .EQU	H'08            ;
XDBSTR: .EQU	H'10            ;
XPIT15: .EQU	H'20            ;
XITALC: .EQU	H'40            ;
XUNDLN: .EQU	H'80            ;
;
PTMD2F: .RES.B	  1		; PRINT MODE 2 FLAG
QJSTF0: .EQU	  0		; *JUSTIFICATION 0 (0,0 = LEFT	/ 0,1 = CENTER)
QJSTF1: .EQU	  1		; *JUSTIFICATION 1 (1,0 = RIGHT / 1,1 = FULL)
QOCRMD: .EQU	  2		; OCR-B MODE
QPRUDI: .EQU	  3		; PRINT UNI-DIRECTION MODE
QLQMD:	.EQU	  4		;+ LETTER QUALITY MODE
QDWLCH: .EQU	  5		; DOWNLOAD CHARACTER
QNOULC: .EQU	  6		; NO UNDERLINE CHARACTER
QCGGRP: .EQU	  7		; GRAPHIC CHARACTER FLAG
	;
XJSTF0: .EQU	H'01            ;
XJSTF1: .EQU	H'02            ;
XOCRMD: .EQU	H'04            ;
XPRUDI: .EQU	H'08            ;
XLQMD:	.EQU	H'10            ;
XDWLCH: .EQU	H'20            ;
XNOULC: .EQU	H'40            ;
XCGGRP: .EQU	H'80            ;
	;
XJSTMK: .EQU	XJSTF0+XJSTF1	; JUSTIFICATION MASK
;
PTMD3F: .RES.B	  1		; PRINT MODE 3 FLAG
QCOLRM: .EQU	  0		;+ *COLOR (RIBBON) MAGENTA (RED-BLACK FOR RED RIBBON)
QCOLRC: .EQU	  1		;+ *COLOR (RIBBON) CYAN
QCOLRY: .EQU	  2		;+ *COLOR (RIBBON) YELLOW
QCOLRB: .EQU	  3		;+ COLOR (RIBBON) BLACK (RED-BLACK FOR BLACK RIBBON)
;	.EQU	  45		; << Free bit >>
QCGST0: .EQU	  6		; CG SET SELECT 0
QCGST1: .EQU	  7		; CG SET SELECT 1
	;
XCOLRM: .EQU	H'01            ;
XCOLRC: .EQU	H'02            ;
XCOLRY: .EQU	H'04            ;
XCOLRB: .EQU	H'08            ;
;	.EQU	H'10            ;
;	.EQU	H'20            ;
XCGST0: .EQU	H'40            ;
XCGST1: .EQU	H'80            ;
	;
XCGFMK: .EQU	XCGST0+XCGST1	; CG-SET FLAG + GRAPHIC FLAG MASK
XCOLMK: .EQU	XCOLRM+XCOLRC+XCOLRY+XCOLRB	; COLOR PARAMETER MASK
;
PTMD4F: .RES.B	  1		; PRINT MODE 4 FLAG (KANJI 1)
QKJVRT: .EQU	  0		;+ *KANJI VERTICAL
QKJHAF: .EQU	  1		;+ *KANJI HALF
QKJ2UL: .EQU	  2		;+ KANJI 2 DOT UNDERLINE
QKJVEL: .EQU	  3		; *KANJI VERTICAL ENLARGE
QKJQUA: .EQU	  4		;+ *KANJI 1/4 MODE
QKJQLW: .EQU	  5		;+ *KANJI 1/4 MODE LOWER
QKJHAJ: .EQU	  6		; KANJI HALF ADJUST
QKJULN: .EQU	  7		;+ *KANJI UNDERLINE
	;
XKJVRT: .EQU	H'01            ;
XKJHAF: .EQU	H'02            ;
XKJ2UL: .EQU	H'04            ;
XKJVEL: .EQU	H'08            ;
XKJQUA: .EQU	H'10            ;
XKJQLW: .EQU	H'20            ;
XKJHAJ: .EQU	H'40            ;
XKJULN: .EQU	H'80            ;
	;
XKJFMK: .EQU	XKJ2UL+XKJHAJ	; KANJI FLAG MASK (FS + !)
;
PTMD5F: .RES.B	  1		; PRINT MODE 5 FLAG (KANJI 2)
QKJMD:	.EQU	  0		; KANJI MODE
QKJCBM: .EQU	  1		; KANJI COMBINE MODE
QKJCB2: .EQU	  2		; KANJI COMBINE MODE 2ND
QKHSMD: .EQU	  3		; KANJI HIGH SPEED MODE
; 4 Bit use ..: 20CPI Flag Check bit...
; 5 Bit use ..: Image Flag Check bit...
ZUPPRO: .EQU	  6		; 921111
ZLOPRO: .EQU	  7		; 921111
;
XKJMD:	.EQU	H'01            ;
XKJCBM: .EQU	H'02            ;
XKJCB2: .EQU	H'04            ;
XKHSMD: .EQU	H'08            ;
;	.EQU	H'10            ;
;	.EQU	H'20            ;
;	.EQU	H'40            ;
;	.EQU	H'80            ;
;
VTCHNF: .RES.B	  1		; VT CHANNEL FLAG
;QVTC0: .EQU	  0		; VT CHANNEL 0
;QVTC1: .EQU	  1		; VT CHANNEL 1
;QVTC2: .EQU	  2		; VT CHANNEL 2
;QVTC3: .EQU	  3		; VT CHANNEL 3
;QVTC4: .EQU	  4		; VT CHANNEL 4
;QVTC5: .EQU	  5		; VT CHANNEL 5
;QVTC6: .EQU	  6		; VT CHANNEL 6
;QVTC7: .EQU	  7		; VT CHANNEL 7
;
COLORF: .RES.B	  1		; 1 LINE COLOR SAVE FLAG (ESC & PRINT MODULE)
QCOLMP: .EQU	  0		; MAGENTA DATA PRESENT (RED-BLACK FOR RED RIBBON)
QCOLCP: .EQU	  1		; CYAN DATA PRESENT
QCOLYP: .EQU	  2		; YELLOW DATA PRESENT
QCOLBP: .EQU	  3		; BLACK DATA PRESENT (RED-BLACK FOR BLACK RIBBON)
;	.EQU	4->5		; << Free bit >>
QCP7P:	.EQU	  6		; COPY 7P MODE FLAG
QCLMLT: .EQU	  7		; COLOR MULTI FLAG
	;
XCOLMP: .EQU	H'01            ;
XCOLCP: .EQU	H'02            ;
XCOLYP: .EQU	H'04            ;
XCOLBP: .EQU	H'08            ;
;	.EQU	H'10            ;
;	.EQU	H'20            ;
XCP7P:	.EQU	H'40            ;
XCLMLT: .EQU	H'80            ;
;
PRPTCF: .RES.B	  1		; 1 LINE PRINT PITCH SAVE FLAG (ESC & PRINT MODULE)
QPT360: .EQU	  0		; 1/360 inch
QPT240: .EQU	  1		; 1/240 inch
QPT180: .EQU	  2		; 1/180 inch
QPT120: .EQU	  3		; 1/120 inch
;	.EQU	  4		; << Free bit >>
QPRRVS: .EQU	  5		; PRINT REVERSE
QBCDPR: .EQU	  6		; BAR CODE PROCESS FOR 1 LINE
QUDPMD: .EQU	  7		; PRINT UNI-DIRECTION
	;
XPT360: .EQU	H'01            ;
XPT240: .EQU	H'02            ;
XPT180: .EQU	H'04            ;
XPT120: .EQU	H'08            ;
;	.EQU	H'10            ;
XPRRVS: .EQU	H'20            ;
XBCDPR: .EQU	H'40            ;
XUDPMD: .EQU	H'80            ;
;
PRMODF: .RES.B	  1		; PRINT VARIATION FLAG (ESC & PRINT MODULE)
QDBSTP: .EQU	  0		; DOUBLE-STRIKE PRESENT
QDBST2: .EQU	  1		; DOUBLE-STRIKE PRESENT MULTI
QAKVEP: .EQU	  2		; ANK VERTICAL ENLARGE PRESENT
QAKRLP: .EQU	  3		; ANK RULED LINE PRESENT
QKJVEP: .EQU	  4		; KANJI VERTICAL ENLARGE PRESENT
QKJULP: .EQU	  5		; KANJI UNDERLINE PRESENT
QKJOLP: .EQU	  6		; KANJI OVERLINE PRESENT
QIMGPR: .EQU	  7		; IMAGE DATA PRESENT
	;
XDBSTP: .EQU	H'01            ;
XDBST2: .EQU	H'02            ;
XAKVEP: .EQU	H'04            ;
XAKRLP: .EQU	H'08            ;
XKJVEP: .EQU	H'10            ;
XKJULP: .EQU	H'20            ;
XKJOLP: .EQU	H'40            ;
XIMGPR: .EQU	H'80            ;
;
UMOD02: .RES.B	  1		; DEFAULT HAN/ENG & UNI/BI-DIR 911223
UMOD03: .RES.B	  1		; DEFAULT COLOR DEFINE 1224
;
;	<< APPLICATION SAVE AREA DEFINE < 1 byte Area > >>
;
ANKSPS: .RES.B	  1		; ANK SPACE COUNTER SAVE
KFSPLS: .RES.B	  1		; KANJI FULL SPACE LEFT SAVE
KFSPRS: .RES.B	  1		; KANJI FULL SPACE RIGHT SAVE
KHSPLS: .RES.B	  1		; KANJI HALF SPACE LEFT SAVE
KHSPRS: .RES.B	  1		; KANJI HALF SPACE RIGHT SAVE
VTCHNS: .RES.B	  1		; VT CHANNEL SAVE AREA
BCDHTS: .RES.B	  1		; BAR CODE HEIGHT SIZE SAVE AREA
PNLELS: .RES.B	  1		; CURRENT PANEL ENLARGE SIZE SAVE AREA
KJCDS1: .RES.B	  1		; KANJI CODE 1ST SAVE AREA
KJCDS2: .RES.B	  1		; KANJI CODE 2ND SAVE AREA
ESCKES: .RES.B	  1		; ESC + K ENTRY POINT NUMBER SAVE
ESCLES: .RES.B	  1		; ESC + L ENTRY POINT NUMBER SAVE
ESCYES: .RES.B	  1		; ESC + Y ENTRY POINT NUMBER SAVE
ESCZES: .RES.B	  1		; ESC + Z ENTRY POINT NUMBER SAVE
EDWKS1: .RES.B	  1		; EDIT WORK SAVE AREA 1
EDWKS2: .RES.B	  1		; EDIT WORK SAVE AREA 2
EDWKS3: .RES.B	  1		; EDIT WORK SAVE AREA 3
EDWKS4: .RES.B	  1		; EDIT WORK SAVE AREA 4
EDWKS5: .RES.B	  1		; EDIT WORK SAVE AREA 5
EDWKS6: .RES.B	  1		; EDIT WORK SAVE AREA 6
;
;	<< APPLICATION SAVE AREA DEFINE 2 < 2 byte Area > >>
;
	.ALIGN	  2
LMARGS: .RES.W	  1		; LEFT MARGIN SAVE AREA
RMARGS: .RES.W	  1		; RIGHT MARGIN SAVE AREA
DATLNS: .RES.W	  1		; DATA OR IMAGE LENGTH SAVE AREA
CLMCTC: .RES.W	  1		; CURRENT COLUMN COUNTER
STCLMC: .RES.W	  1		; START COLUMN COUNTER
IMGBFP: .RES.W	  1		; IMAGE BUFFER POINTER
TXTBFP: .RES.W	  1		; TEXT BUFFER POINTER
CLMSVS: .RES.W	  1		; COLUMN SAVE AREA
CLMMXS: .RES.W	  1		; COLUMN MAX SAVE AREA
JUSADC: .RES.W	  1		; OTHER JUSTIFICATION ADJUST COLUMN (RMARG. - CLM.MAX)
JUSWDS: .RES.W	  1		; (RMARG. - LMARG.) x 0.75 FOR FULL JUSTIFICATION
JUSSPC: .RES.W	  1		; SPACE BLOCK COUNTER FOR FULL JUSTIFICATION
JSSPS1: .RES.W	  1		; SPACE BLOCK ADJUST VALUE SAVE AREA
JSSPS2: .RES.W	  1		; SPACE BLOCK REMAINDER OF ADJUST VALUE SAVE AREA
CHRWDS: .RES.W	  1		; CHARACTER WIDTH SAVE AREA
UMOD04: .RES.B	  1		; PANNEL MODE sellect 911226


;--------------------------------------------
UMOD05: .RES.B	  1		; 920309
QDREVS: .EQU	  0		; REVERSE
QDAMIK: .EQU	  1		; AMIKAKE
QDGODI: .EQU	  2		; HANGUL GODIC/MYEONGJO
QKMSKF: .EQU	  3		; MASKING BLOCK FLAGE	920327
QKCOMB: .EQU	  4		; Combination font using. 920409
;
QAUTOR: .EQU	  5		; 921006
;
KUPPRO: .EQU	  6		; DH UPPER PART
KLOPRO: .EQU	  7		; DH LOWER PART
;---------------------------------------------
IBMCDV1: .RES.B   1		; 920207 NBYTE
NSTCNT:  .RES.B   1		;	"
IBMCDV2: .RES.B   1		; 920207 NBYTE
IBMCDV3: .RES.B   1		; 920207 NBYTE
ORGDAT:  .RES.B   1		; 920207 NBYTE
IBMCTV:  .RES.B   1		;	 NBYTE
IBMCDV0: .RES.B   1		;	 NBYTE
;---------------------------------------------
UMOD06: .RES.B	 1		;
RHGDW:	.EQU	 0		; HG ONLY DW 930206
RCONN:	.EQU	 1		; 930406 VT-CONNECTION
;		2 - 7		; FREE BIT
;MSKVAL: .RES.B   1		 ; MASKING VALUE

    .RES.B  1
BFCNT1: .EQU    IBMCDV2
BFCNT2: .EQU    IBMCDV3
;
;    .RES.B   1      ; CAN'T USE
;
	.LIST	ON
