	.LIST	OFF
;********************************************************
;							*
;	M4324 I/O SYSTEM USER OWN CODE DEFINITION	*
;							*
;	FILE NAME	AX_IOS.H			*
;	CREATED		18/JAN/1991			*
;							*
;********************************************************
;
;	I/O SYSTEM USER OWN CODE CALL ENTRY
;
	.IMPORT		BZBEL	; BELL TONE ON
	.IMPORT		BZPSW	; PANEL SW CLICK TONE
	.IMPORT		BZMDC	; MODE CHANGE TONE ON
	.IMPORT		BZEON	; CHECK ERROR TONE ON
	.IMPORT		BZEOF	; CHECK ERROR TONE OFF
	.IMPORT		DSPALM	; DISPLAY ALARM ERROR
	.IMPORT		DSPPON	; DISPLAY POWER ON MODE
	.IMPORT		DSPSTA	; DISAPLY NORAML MODE START
	.IMPORT		DSPNOR	; DISPLAY NORMAL MODE
	.IMPORT		DSPPAM	; DISPLAY PAPER MODE
	.IMPORT		DSPCPM	; DISPLAY COPY MODE
	.IMPORT		DSPPFN	; DISPLAY PRINT FORMAT NO.
	.IMPORT		DSPMDC	; DISPLAY MODE CHANGE MESSAGE
	.IMPORT		DSPADS	; DISPLAY TOP SENSOR A/D VALUE
	.IMPORT		DSPCUR	; DISPLAY BLINK CURSOR
	.IMPORT		DSPMEN	; DISPLAY MENU
	.IMPORT		DSPLST	; DISPLAY LIST
	.IMPORT		DSPCOF	; DISPLAY CURSOR OFF
	.IMPORT		DSPCON	; DISPLAY CURSOR ON
	.IMPORT		DSPCHR	; DISPLAY CHARCTER
	.IMPORT		DSPKCP	; DISPLAY 2 KANJI CHARACTER PITCH
	.IMPORT		DSPDE2	; DISPLAY 2 DIGIT DECIMAL
	.IMPORT		DSPHX1	; DISPLAY 1 DIGIT HEX
	.IMPORT		DSPHX2	; DISPLAY 2 DIGIT HEX
	.IMPORT		DSPHX4	; DISPLAY 4 DIGIT HEX
	.IMPORT		DSPHXS	; DISPLAY 2 DIGIT SIGNED HEX
	.IMPORT		EESAVE	; SAVE EEPROM DATA
	.IMPORT		SCIEEP	; SEND EEPROM DATA TO SLAVE CPU
	.IMPORT		SCIPAJ	; SEND EEPROM PRINT ADJUST DATA TO SLAVE CPU
	.LIST	ON
