	.LIST	OFF
;********************************************************
;							*
;	M4324 MONITOR TASK DEFINITION			*
;							*
;	FILE NAME	AX_MON.H			*
;	CREATED		29/OCT/1990			*
;							*
;********************************************************
;
;	EVENT FLAG
;
;FACTF:	.EQU	H'0001		; DP3 ACTION FINISH
FSALM:	.EQU	H'0002		; SET ALARM ERROR   MODE
FMOND:	.EQU	H'0004		; SET MONITOR DISABLE
FMONE:	.EQU	H'0008		; SET MONITOR ENABLE
FCCVR:	.EQU	H'0010		; CHECK COVER STATUS
FCHSM:	.EQU	H'0020		; CHECK HEAD SHIFT MODE
FC260:	.EQU	H'0040		; CHECK SF260 STATUS
FSPED:	.EQU	H'0080		; SET PE CHECK DISABLE
FSPEE:	.EQU	H'0100		; SET PE CHECK ENABLE
FCPES:	.EQU	H'0200		; CHECK PE STATUS
FRPRE:	.EQU	H'0400		; RESET PRINT ENABLE MODE
FRPEO	.EQU	H'0800		; RESET PE OVVERIDE MODE
FSPRE:	.EQU	H'1000		; SET PRINT ENABLE  MODE
FSPRO:	.EQU	H'2000		; SET PRINT ENABLE  MODE  (PE OVERRIDE ENABLE)
QCPES:	.EQU	  9		;
	.LIST	ON
