	.LIST	OFF
	.SECTION	APLRAM,DUMMY,LOCATE=H'FE00
;********************************************************
;							*
;	M4324 APPLICATION WORK RAM DEFINITION		*
;							*
;	FILE NAME	AX_RAM.H			*
;	CREATED 	21/DEC/1990			*
;							*
;********************************************************
;
;	BIT REASSIGN IN SYSTEM RAM
;
;SWSF:	.RES.W	  1		; PANEL SW STATUS FLAG
QSW1:	.EQU	  0		;   1:SW1  ON
QSW2:	.EQU	  1		;   1:SW2  ON
QSW3:	.EQU	  2		;   1:SW3  ON
QSW4:	.EQU	  3		;   1:SW4  ON
QSW5:	.EQU	  4		;   1:SW5  ON
QSW6:	.EQU	  5		;   1:SW6  ON
QSW7:	.EQU	  6		;   1:SW7  ON
QSW8:	.EQU	  7		;   1:SW8  ON
QSW9:	.EQU	  8		;   1:SW9  ON
QSW10:	.EQU	  9		;   1:SW10 ON
QSW11:	.EQU	 10		;   1:SW11 ON
QCVSW:	.EQU	 11		;   1:COVER CLOSE
QSW12:	.EQU	 12		;   1:SW12 ON
;	.EQU	 13		;     ALWAYS 0
;	.EQU	 14		;     ALWAYS 0
;	.EQU	 15		;     ALWAYS 0
XSW1:	.EQU	H'0001          ;
XSW2:	.EQU	H'0002          ;
XSW3:	.EQU	H'0004          ;
XSW4:	.EQU	H'0008          ;
XSW5:	.EQU	H'0010          ;
XSW6:	.EQU	H'0020          ;
XSW7:	.EQU	H'0040          ;
XSW8:	.EQU	H'0080          ;
XSW9:	.EQU	H'0100          ;
XSW10:	.EQU	H'0200          ;
XSW11:	.EQU	H'0400          ;
XSW12:	.EQU	H'1000          ;

;LEDF:	.RES.B	  1		; LED STATUS FLAG
QLALM:	.EQU	  0		;   0:ALARM LED ON
QLCHK:	.EQU	  1		;   0:CHECK LED ON
QLMNH:	.EQU	  2		;   0:MANUAL HEAD SHIFT MODE LED ON
;	.EQU	  3		;
QLON:	.EQU	  4		;   0:ONLINE LED ON
;	.EQU	  5		;
QLLOAD: .EQU	  6		;   0:LOAD LED ON
;	.EQU	  7		;
XLALM:	.EQU	H'01            ;
XLCHK:	.EQU	H'02            ;
XLMNH:	.EQU	H'04            ;
XLON:	.EQU	H'10            ;
XLLOAD: .EQU	H'40            ;

;PSWDF: .RES.B	  1		; PANEL SW DISABLE FLAG
;QDALM: .EQU	  0		;   1:DISABLE BY ALARM ERROR
QDIPR:	.EQU	  1		;   1:DISABLE BY INPUT PRIME
QDCVR:	.EQU	  2		;   1:DISABLE BY COVER ERROR
QDOFF:	.EQU	  3		;   1:DISABLE BY OFFLINE CHANGE
QDPFC:	.EQU	  4		;   1:DISABLE BY PF CHANGE
QDMDC:	.EQU	  5		;   1:DISABLE BY MODE CHANGE
QDTPR:	.EQU	  6		;   1:DISABLE BY TEST PRINT
;	.EQU	  7		;

;
;	APPLICATION RAM
;
;
CURDF:	.RES.W	  1		; LCD CURSOR DISPLAY FLAG
QCURON: .EQU	  7		;   1:CURSOR ON REQUEST

OPTF:	.RES.B	  1		; OPTION ATTACHMENT FLAG
;	.EQU	  0		;
QRBRBN: .EQU	  0		;   1:READ/BLACK RIBBON
;QLBUSY:.EQU	  2		;   1:LINE BUSY MODE
QBRBN:	.EQU	  3		;   0:BLACK RIBBON
;QSELA: .EQU	  4		;     ASCF TYPE SELECT
QNOACF: .EQU	  5		;   1:ACSF NOT ATTACHED
;QMNSW: .EQU	  6		;     ACSF MANUAL/AUTO SW
QSIFM:	.EQU	  7		;   1:SERIAL I/F MODE

DIPF:	.RES.B	  1		; DIP SW FLAG
;QDIP1: .EQU	  0		;	1:DIP-SW1 ON
;QDIP2: .EQU	  1		;	1:DIP-SW2 ON
;QDIP3: .EQU	  2		;	1:DIP-SW3 ON
;QDIP4: .EQU	  3		;	  NO FUNCTION
QSLIN:	.EQU	  4		;	0:SELECT IN HIGH
;	.EQU	  5		;	  NO FUNCTION
;	.EQU	  6		;	  NO FUNCTION
QATFE:	.EQU	  7		;	0:AUTO FEED XT HIGH

ERRF:	.RES.B	  1		; ERROR FLAG
QPE1ER: .EQU	  0		;   1:PE EEROR BEFORE EJECT
QPE2ER: .EQU	  1		;   1:PE ERROR AFTER  EJECT
QINSER: .EQU	  2		;   1:INSERT ERROR
QEJCER: .EQU	  3		;   1:EJECT  ERROR
QPMDER: .EQU	  4		;   1:PAPER MODE ERROR
Q260ER: .EQU	  5		;   1:SF-260 STACKER ERROR
;	.EQU	  6		;
QCVRER: .EQU	  7		;   1:COVER OPEN ERROR
XPE1ER: .EQU	H'01            ;
XPE2ER: .EQU	H'02            ;
XINSER: .EQU	H'04            ;
XEJCER: .EQU	H'08            ;
XPMDER: .EQU	H'10            ;
X260ER: .EQU	H'20            ;
XCVRER: .EQU	H'80            ;

MODEF:	.RES.B	  1		; FUNCTION MODE FLAG
QPREM:	.EQU	  0		;   1:PRINT ENABLE MODE
QFACTM: .EQU	  1		;   1:FACTORY MODE
QIPRM:	.EQU	  2		;   1:INPUT PRIME INITIALIZE MODE
;	.EQU	  3		;
QPFCM:	.EQU	  4		;   1:PRINT FORMAT CHANGE MODE
QSPCM:	.EQU	  5		;   1:SPECIFICATION CHANGE MODE
QSERVM: .EQU	  6		;   1:SERVICE MODE
;	.EQU	  7		;
XPREM:	.EQU	H'01            ;
XFACTM: .EQU	H'02            ;
XPFCM:	.EQU	H'10            ;
XSPCM:	.EQU	H'20            ;
XSERVM: .EQU	H'40            ;

PRMDF:	.RES.B	  1		; PRINT MODE FLAG
QHDCM:	.EQU	  0		;   1:HEAD COOLING MODE
QINSM:	.EQU	  1		;   1:PAPER INSERT MODE
Q7PM:	.EQU	  2		;   1:COPY ENHANCE MODE
QPEOVM: .EQU	  3		;   1:PE OVERRIDE MODE
QPRTA:	.EQU	  4		;   1:PRINT JOB ACTIVE
QDP3S:	.EQU	  5		;   1:DP3 SUSPEND
QDP3M:	.EQU	  6		;   1:DP3 MULTI BLOCK MODE
QPRFST: .EQU	  7		;   1:FIRST PRINT DATA RECEIVED

DPMDF:	.RES.B	  1		; DATA PROCESS MODE FLAG
ZNDAP:	.EQU	  0		;     NORMAL DATA PROCESS MODE
ZSPRA:	.EQU	  1		;     SELF PRINT A MODE
ZSPRB:	.EQU	  2		;     SELF PRINT B MODE
ZSPRC:	.EQU	  3		;     SELF PRINT C MODE
ZHDPW:	.EQU	  4		;     HEX DUMP WIDE MODE
ZHDPN:	.EQU	  5		;     HEX DUMP NARROW MODE
QHDPM:	.EQU	  2		;   1:HEX DUMP MODE

PSPDF:	.RES.B	  1		; PRINT SPEED FLAG
ZPS10:	.EQU	  0		;     NATIVE PRINT SPEED
ZPS15:	.EQU	  1		;     x1.5 PRINT SPEED
ZPS20:	.EQU	  2		;     x2.0 PRINT SPEED
ZPS30:	.EQU	  3		;     x3.0 PRINT SPEED

PAMDF:	.RES.B	  1		; PAPER MODE FLAG
ZFORM:	.EQU	  0		;     FORMS MODE
ZFORMP: .EQU	  1		;     FORMS MODE   (PAPER HOTCHKISS)
ZBTM:	.EQU	  2		;     BOTTOM MODE
ZBTMP:	.EQU	  3		;     BOTTOM MODE  (PAPER HOTCHKISS)
ZSHT:	.EQU	  4		;     SHEET MODE
ZACF0:	.EQU	  5		;     ACSF0 MODE   (SF-260)
ZACF1:	.EQU	  6		;     ACSF1 MODE   (BIN 1)
ZACF2:	.EQU	  7		;     ACSF2 MODE   (BIN 2)
ZACF3:	.EQU	  8		;     ACSF3 MODE   (BIN 3 AUTO)
ZACF4:	.EQU	  9		;     ACSF4 MODE   (BIN 3 MANUAL)

DABDC:	.RES.W	  1		; DATA BUFFER DATA COUNTER
	.RES.B	  4		; RESERVED AREA
	.LIST	ON
