	.LIST	OFF
;********************************************************
;							*
;	M4324 AX TEXT BUFFER FORMAT DEFINITION		*
;							*
;	FILE NAME	AX_TBF.H			*
;	CREATED 	23/MAR/1990			*
;							*
;********************************************************
;
;	<< SPECIAL FUNCTION CODE IN TEXT BUFFER >>
;
ZTBCLF: .EQU	  0		; SPECIFY RELATIVE COLUMN POSITION (FORWARD)
ZTBCLR: .EQU	  1		; SPECIFY RELATIVE COLUMN POSITION (REVERSE)
ZTBCLU: .EQU	  2		; SPECIFY ABSOLUTE COLUMN POSITION (UNDERLINE)
ZTBFDF: .EQU	  3		; FEED FORTH (ESC + J)
ZTBFDB: .EQU	  4		; FEED BACKWARD (ESC + j)
;
;	<< TEXT BUFFER FORMAT SIZE CONSTANT >>
;
ZFMTSZ: .EQU	 12		;\ 9/MAR/1992 FORMAT SIZE
ZCMNSZ: .EQU	  5		; COMMON FORMAT SIZE
;
;	<< TEXT BUFFER FORMAT FLAG CONSTANT >>
;
ZENDMK: .EQU	H'00            ; END MARK FORMAT FLAG
ZANKFM: .EQU	H'01            ; ANK CODE FORMAT FLAG
ZKNJFM: .EQU	H'02            ; KANJI CODE FORMAT FLAG
ZCMBFM: .EQU	H'03            ; KANJI CODE COMBINE FORMAT FLAG
ZIMGFM: .EQU	H'04            ; IMAGE DATA FORMAT FLAG
ZHTBFM: .EQU	H'05            ; HORIZONTAL TAB FORMAT FLAG
ZCLMFM: .EQU	H'06            ; COLUMN COMMAND FORMAT FLAG
ZFEDFM: .EQU	H'07            ; FEED COMMAND FORMAT FLAG
ZJ13FM: .EQU	H'08            ; BAR-CODE JAN 13 FORMAT FLAG
ZJ08FM: .EQU	H'09            ; BAR-CODE JAN 08 FORMAT FLAG
ZCDBFM: .EQU	H'0A            ; BAR-CODE CODER BAR FORMAT FLAG
ZC39FM: .EQU	H'0B            ; BAR-CODE CODE 39 FORMAT FLAG
	;
Z10SPD: .EQU	H'00            ; PRINT SPEED   = 1.0   MODE (IMAGE or EDITING)
Z10ASP: .EQU	H'01            ;               = 1.0-A MODE (KANJI or BAR-CODE)
Z10BSP: .EQU	H'02            ;               = 1.0-B MODE (ANK FOR LQ)
Z10CSP: .EQU	H'03            ;               = 1.0-C MODE
Z10DSP: .EQU	H'04            ;               = 1.0-D MODE
Z15SPD: .EQU	H'05            ;               = 1.5   MODE
Z20SPD: .EQU	H'06            ;               = 2.0   MODE
Z30SPD: .EQU	H'07            ;               = 3.0   MODE (ANK FOR DRAFT)
	;
Z360P:	.EQU	  4		; PRINT PITCH	= 1/360 INCH
Z240P:	.EQU	  5		;		= 1/240 INCH
Z180P:	.EQU	  6		;		= 1/180 INCH
Z120P:	.EQU	  7		;		= 1/120 INCH
	;
ZSPDMK: .EQU	H'0F            ; TEXT BUFFER SPEED FLAG MASK
ZPTCMK: .EQU	H'F0            ; TEXT BUFFER PITCH FLAG MASK
;
;	<< TEXT BUFFER MODE FLAG CONSTANT >>
;
;		QAxxx -> ANK   FLAG BITS
;		QKxxx -> KANJI FLAG BITS
;		QPxxx -> ANK/KANJI COMMON FLAG BITS
;
QAELIT: .EQU	  0		; ELITE
QAPROP: .EQU	  1		; PROPORTIONAL
QACOND: .EQU	  2		; CONDENSE
QPEMPH: .EQU	  3		; EMPHASIZE	     << COMMON >>
QALQMD: .EQU	  4		; LQ MODE
QAP15C: .EQU	  5		; 15 CPI
QPITLC: .EQU	  6		; ITALIC	     << COMMON >>
QAUNDL: .EQU	  7		; ANK UNDERLINE
;	.EQU	  8		; << Free bit >>
QASUPS: .EQU	  9		; SUPERSCRIPT
QASUBS: .EQU	 10		; SUBSCRIPT
QPOUTL: .EQU	 11		; OUTLINE	     << COMMON >>
QPSHDW: .EQU	 12		; SHADOW	     << COMMON >>
QAVENL: .EQU	 13		; ANK VERTICAL ENLARGE
QPHENL: .EQU	 14		; HORIZONTAL ENLARGE << COMMON >>
;	.EQU	 15		; << Free bit >>
	;
QKVFMT: .EQU	  0		; VERTICAL FORMAT
QKHALF: .EQU	  1		; KANJI HALF
QK2ULN: .EQU	  2		; 2 DOTS UNDERLINE
QKJ14:	.EQU	  4		; 1/4 MODE
QKJ14L: .EQU	  5		; 1/4 LOWER
QKUNDL: .EQU	  7		; KANJI UNDERLINE
;	.EQU	  8		; << Free bit >>
QKEISN: .EQU	  9		; KEISEN SETSUZOKU MODE
QKJ2ND: .EQU	 10		; KANJI COMBINE 2ND CODE
QKVENL: .EQU	 13		; KANJI VERTICAL ENLARGE
;	.EQU	 15		; << Free bit >>
;
;\ 9/MAR/1992
QPREVS: .EQU	  0		; REVERSE MODE
QPAMIK: .EQU	  1		; AMIKAKE
QKGODI: .EQU	  2		; HANGUL GODIC/MYEONG
QPMSKF: .EQU	  3		; MASKING BLOCK
QPCOMB: .EQU	  4		; Combination font using.
;
MUPPRO: .EQU	  6		; DH UPPER PART
MLOPRO: .EQU	  7		; DH LOWER PART
;
;
;	<< TEXT BUFFER OFFSET CONSTANT < 1 FORMAT > >>
;
YFMATF: .EQU	  0		; FORMAT FLAG		OFFSET < COMMON >
YCOLRF: .EQU	  1		; COLOR FLAG		OFFSET < COMMON >
YBSPDF: .EQU	  1		; BAR CODE SPEED/PITCH	OFFSET < COMMON >
YCLMCF: .EQU	  2		; COLUMN COUNTER	OFFSET < COMMON >
YSPDPF: .EQU	  4		; SPEED/PITCH		OFFSET < COMMON >
	;
YPRESP: .EQU	  5		; PRE. SPACE		OFFSET < PRINT DATA >
YRSRV1: .EQU	  5		; RESERVE 1 AREA	OFFSET < IMAGE >
YDIRFG: .EQU	  5		; DIRECTION FLAG	OFFSET < COLUMN >
YPKTCD: .EQU	  5		; PACKET CODE		OFFSET < FEED >
YCODEF: .EQU	  6		; ANK / KANJI CODE	OFFSET < PRINT DATA >
Y2NDCD: .EQU	  6		; COMBINE 2ND CODE	OFFSET < PRINT DATA >
YRCLMC: .EQU	  6		; RELATIVE COLUMN SIZE	OFFSET < COLUMN >
YIMGST: .EQU	  6		; IMAGE START ADDRESS	OFFSET < IMAGE >
YABSFD: .EQU	  6		; ABSOLUTE FEED VALUE	OFFSET < FEED >
YMODEF: .EQU	  8		; MODE FLAG		OFFSET < PRINT DATA >
YRSERV: .EQU	  8		; RESERVE 2 AREA	OFFSET < COLUMN/FEED >
YIMGED: .EQU	  8		; IMAGE END   ADDRESS	OFFSET < IMAGE >
YMODKF: .EQU	 10		; EX_AREA		OFFSET < PRINT DATA >
YBCKSP: .EQU	 11		; BACK SPACE		OFFSET < PRINT DATA >
	.LIST	ON
