	.LIST	OFF
	.SECTION	GAHEAD,DUMMY,LOCATE=H'4000
;********************************************************
;							*
;	PRINT HEAD CONTROL GA DEFINITION		*
;							*
;	FILE NAME	GAHEAD.H			*
;	CREATED		 2/OCT/1990			*
;							*
;********************************************************
;
;	PRINT HEAD CONTROL GA 1
;
DCR0:	.RES.B	  1		; R   DOT COUNT REGISTER (LOW)
DCR1:	.RES.B	  1		; R   DOT COUNT REGISTER (HIGH)
	.RES.B	  1		;
BSP0:	.RES.B	  1		; W   BUFFER START POINTER (LOW)
BSP1:	.RES.B	  1		; W   BUFFER START POINTER (HIGH)
BSP2:	.RES.B	  1		; W   BUFFER START POINTER (LOW)
BSP3:	.RES.B	  1		; W   BUFFER START POINTER (HIGH)
BEP0:	.RES.B	  1		; W   BUFFER END POINTER (LOW)
BEP1:	.RES.B	  1		; W   BUFFER END POINTER (HIGH)
BEP2:	.RES.B	  1		; W   BUFFER END POINTER (LOW)
BEP3:	.RES.B	  1		; W   BUFFER END POINTER (HIGH)
OVLT1:	.RES.B	  1		; W   DUTY OVER LIMIT REGISTER (LOW)
OVLT2:	.RES.B	  1		; W   DUTY OVER LIMIT REGISTER (HIGH)
UNCNT:	.RES.B	  1		; W   DUTY UNIT CONTROL REGISTER
XWWR:	.EQU	H'01		; W	1:RESET DUTY COUNTER
XPS1:	.EQU	H'02		; W	00:10*8 COLUMN	01:20*8 COLUMN
XPS2:	.EQU	H'04		; W	10:30*8 COLUMN	11:INHIBIT
XOVR:	.EQU	H'08		; W	1:RESET DUTY COUNTER, XOVDF
XDEL1:	.EQU	H'10		; W	00:NO DELETE	01:1 DOT DELETE
XDEL2:	.EQU	H'20		; W	10:2 DOT DELETE 11:INHIBIT
;	.EQU	H'40		;
;	.EQU	H'80		;

CTRL:	.RES.B	  1		;R/W  CONTROL REGISTER
XOUTE:	.EQU	H'01		;R/W	1:OUTPUT ENABLE
XRAM64:	.EQU	H'02		;R/W	0:64K BIT RAM
XSPD2:	.EQU	H'04		; R	00:x1	01:x2
XSPD3:	.EQU	H'08		; R	10:x3	11:NO FUNCTION
;	.EQU	H'10		;
XCTRS:	.EQU	H'20		; W	1:RESET DCR, DUTY COUNTER, XOVDF
;	.EQU	H'40		;
XRAMS:	.EQU	H'80		;R/W	0:RAM A SELECT	1:RAM B
QOUTE:	.EQU	  0		;
QCTRS:	.EQU	  5		;
QRAMS:	.EQU	  7		;

OVD:	.RES.B	  1		; R   OVER DUTY STATUS REGISTER
QOVDF:	.EQU	  0		; R	1:OVER DUTY

PITCNT:	.RES.B	  1		; W   PRINT PITCH CONTROL REGISTER
XDP360:	.EQU	H'01		; W	1:1/360 INCH
XDP240:	.EQU	H'02		; W	1:1/240 INCH
XDP180:	.EQU	H'04		; W	1:1/180 INCH
XDP120:	.EQU	H'08		; W	1:1/120 INCH

	.RES.B	 15		;
;
;	PRINT HEAD CONTROL GA 2
;
	.RES.B	  1		;
DPR:	.RES.B	  1		; W  DOT PITCH REGISTER
;XDP360:.EQU	H'01		; W	1:1/360 INCH
;XDP240:.EQU	H'02		; W	1:1/240 INCH
;XDP180:.EQU	H'04		; W	1:1/180 INCH
;XDP120:.EQU	H'08		; W	1:1/120 INCH

TRA1:	.RES.B	  1		; W   HEAD ON TIME REGISTER A1
TRA2:	.RES.B	  1		; W   HEAD ON TIME REGISTER A2
TRA3:	.RES.B	  1		; W   HEAD ON TIME REGISTER A3
TRB:	.RES.B	  1		; W   HEAD ON TIME REGISTER B
TRC:	.RES.B	  1		; W   HEAD ON TIME REGISTER C
TRD:	.RES.B	  1		; W   HEAD ON TIME REGISTER D
	.RES.B	  1		;
DTR1:	.RES.B	  1		; W   HEAD PIN DELAY TIME REGISTER 1
DTR2:	.RES.B	  1		; W   HEAD PIN DELAY TIME REGISTER 2
DTR3:	.RES.B	  1		; W   HEAD PIN DELAY TIME REGISTER 3
DTR4:	.RES.B	  1		; W   HEAD PIN DELAY TIME REGISTER 4
DTR5:	.RES.B	  1		; W   HEAD PIN DELAY TIME REGISTER 5
DTR6:	.RES.B	  1		; W   HEAD PIN DELAY TIME REGISTER 6
OUTC:	.RES.B	  1		; W   OUTPUT CONTROL REGISTER
XPR2P:	.EQU	H'01		; W	0:1 PASS PRINT	1:2 PASS
XPR2:	.EQU	H'02		; W	0:1ST PASS	1:2ND PASS
XPRE:	.EQU	H'04		; W	1:PRINT ENABLE
XBPL:	.EQU	H'08		; W	1:BOUND PULSE LIMIT ON
XBPE:	.EQU	H'10		; W	1:BOUND PULSE ENABLE
;	.EQU	H'20		;
;	.EQU	H'40		;
XPCL:	.EQU	H'80		; W	0:CHECK PCL CHATTERING
QPR2P:	.EQU	  0		;
	.LIST	ON
