	.LIST	OFF
	.SECTION	GAIFP,DUMMY,LOCATE=H'500D
;********************************************************
;							*
;	I/O EXPANDER GA I/F PORT MODULE DEFINITION	*
;							*
;	FILE NAME	GAIFP.H				*
;	CREATED		14/DEC/1990			*
;							*
;********************************************************
;
IFREAD:	.RES.B	  1		; R   I/F DATA INPUT
DATCLR:	.RES.B	  1		; W   I/F DATA INTERRUPT CLEAR
IFPOTA:	.RES.B	  1		;R/W  I/F PORT A
XFALT:	.EQU	H'01		;	0:FAULT LOW
XHALM:	.EQU	H'02		;	0:HEAD ALARM LOW
XROMS:	.EQU	H'02		;	0:LOWER 1M BIT ROM SELECT
XRMR:	.EQU	H'04		;	0:RMR LOW
XCAN:	.EQU	H'08		;	0:CANCEL LOW
XSEL:	.EQU	H'10		;	0:SELECT LOW
XPE:	.EQU	H'20		;	0:PE LOW
XACK:	.EQU	H'40		;	0:ACK HIGH
XBUSY:	.EQU	H'80		;	0:BUSY HIGH
QFALT:	.EQU	  0		;
QHALM:	.EQU	  1		;
QROMS:	.EQU	  1		;
QRMR:	.EQU	  2		;
QCAN:	.EQU	  3		;
QSEL:	.EQU	  4		;
QPE:	.EQU	  5		;
QACK:	.EQU	  6		;
QBUSY:	.EQU	  7		;

IFPOTB:	.RES.B	  1		;R/W  I/F PORT B
XBIT0:	.EQU	H'01		;
XBIT1:	.EQU	H'02		; R	0:UPPER 1M BIT ROM
XBUSY0:	.EQU	H'04		;	1:BUSY HIGH AT INPUT PRIME 0
XBUSY1:	.EQU	H'08		;	1:BUSY HIGH AT INPUT PRIME 1
XSWPR:	.EQU	H'10		;	0:RESET SW PANEL LSI
XWTON:	.EQU	H'20		;	0:OPTCG WAIT ON
XROMC:	.EQU	H'40		;	0:ROM SELECT ENABLE
XACSF:	.EQU	H'40		;	1:ACSF HIGH
XACSO:	.EQU	H'80		;	1:ACSFON HIGH
QSWPR:	.EQU	  4		;
QWTON:	.EQU	  5		;
QROMC:	.EQU	  6		;
QACSF:	.EQU	  6		;
QACSO:	.EQU	  7		;

IFPOTC:	.RES.B	  1		; R   I/F PORT C
;XDIP1:	.EQU	H'01		;	0:DIP-SW1 ON
;XDIP2:	.EQU	H'02		;	0:DIP-SW2 ON
;XDIP3:	.EQU	H'04		;	0:DIP-SW3 ON
;	.EQU	H'08		;	  NO FUNCTION
;XSLIN:	.EQU	H'10		;	1:SELECT IN HIGH
;XMODE:	.EQU	H'20		;	1:MODE HIGH
;XCNRD:	.EQU	H'40		;	1:CAN READ HIGH
;XATFE:	.EQU	H'80		;	1:AUTO FEED XT HIGH
	.LIST	ON
