	.LIST	OFF
	.SECTION	GAINT,DUMMY,LOCATE=H'5008
;********************************************************
;							*
;	I/O EXPANDER GA INTERRUPT MODULE DEFINITION	*
;							*
;	FILE NAME	GAINT.H				*
;	CREATED		 8/AUG/1990			*
;							*
;********************************************************
;
INTPRE:	.RES.B	  1		; R   INTERRUPT DATA
XIPRM0:	.EQU	H'01		;       1->0:INPUT PRIME 0
XIPRM1:	.EQU	H'02		;       1->0:INPUT PRIME 1
XINTNF:	.EQU	H'04		;	     NO FUNCTION
XTRSRQ:	.EQU	H'08		;	1->0:TRANSMIT REQUEST
XPRBSY:	.EQU	H'10		;	1->0:PRINT END
XSPDIN:	.EQU	H'20		;	1->0:PRINT SPEED CHANGE
XSLBSY:	.EQU	H'40		;	1->0:SLAVE RECEIVE ENABLE
XSLACT:	.EQU	H'80		;	1->0:SLAVE ACTION END
QIPRM0:	.EQU	  0		;
QIPRM1:	.EQU	  1		;
QTRSRQ:	.EQU	  3		;
QPRBSY:	.EQU	  4		;
QSPDIN:	.EQU	  5		;
QSLBSY:	.EQU	  6		;
QSLACT:	.EQU	  7		;

INTREQ:	.RES.B	  1		; R   INTERRUPT REQUEST
INTMSK:	.RES.B	  1		;R/W  INTERRUPT MASK
INTDAT:	.RES.B	  1		;R/W  INTERRUPT LATCHED DATA
INTRST:	.RES.B	  1		; W   INTERRUPT REQUEST RESET TRIGGER
	.LIST	ON
