	.LIST	OFF
	.SECTION	GAIOP,DUMMY,LOCATE=H'5012
;********************************************************
;							*
;	I/O EXPANDER GA I/O PORT MODULE DEFINITION	*
;							*
;	FILE NAME	GAIOP.H 			*
;	CREATED		25/SEP/1990			*
;							*
;********************************************************
;
EXPNDA:	.RES.B	  1		; R   I/O PORT A
XSBUSY:	.EQU	H'01		;	1:SLAVE CPU TRANSMIT BUSY
XSLRE:	.EQU	H'02		;	  SLAVE CPU RECEIVE READY
XLBUSY:	.EQU	H'04		;	1:LINE BUSY MODE
XRBNS:	.EQU	H'08		;	0:BLACK RIBBON
;XSELA:	.EQU	H'10		;	  ASCF TYPE SELECT
;XACSW:	.EQU	H'20		;	0:ACSF ATTACHED
;XMNSW:	.EQU	H'40		;	  ACSF MANUAL/AUTO SW
XPIFD:	.EQU	H'80		;	0:PARALLEL I/F DETECT
QSBUSY:	.EQU	  0		;
QSLRE:	.EQU	  1		;

EXPNDB:	.RES.B	  1		;R/W  I/O PORT B
XEXA16:	.EQU	H'01		;	  EXTEND ADDRESS 16
XEXA17:	.EQU	H'02		;	  EXTEND ADDRESS 17
XEXA18:	.EQU	H'04		;	  EXTEND ADDRESS 18
XEXA19:	.EQU	H'08		;	  EXTEND ADDRESS 19
XFANC:	.EQU	H'10		;	0:FAN ON
XMARE	.EQU	H'20		;	  MAIN CPU RECEIVE READY
XSNMI:	.EQU	H'40		;	0->1:SLAVE CPU RESET
XMBUSY:	.EQU	H'80		;	0:MAIN CPU TRANSMIT BUSY
QEXA16:	.EQU	  0		;
QEXA17:	.EQU	  1		;
QEXA18:	.EQU	  2		;
QEXA19:	.EQU	  3		;
QFANC:	.EQU	  4		;
QMARE:	.EQU	  5		;
QSNMI:	.EQU	  6		;
QMBUSY:	.EQU	  7		;

EXPNDC:	.RES.B	  1		;R/W  I/O PORT C
XBUSYR:	.EQU	H'01		; R	0:BUSY HIGH
XINSWT:	.EQU	H'02		;R/W	1:SW PANEL WAIT ON
	.LIST	ON
