	.LIST	OFF
	.SECTION	GAPNL,DUMMY,LOCATE=H'5000
;********************************************************
;							*
;	I/O EXPANDER GA PANEL MODULE DEFINITION		*
;							*
;	FILE NAME	GAPNL.H				*
;	CREATED		06/MAR/1990			*
;							*
;********************************************************
;
SWPDBA:	.RES.B	  1		;IN   PANEL SW INPUT
;XPSW1:	.EQU	H'01		; R	0:SW1  ON
;XPSW2:	.EQU	H'02		; R	0:SW2  ON
;XPSW3:	.EQU	H'04		; R	0:SW3  ON
;XPSW4:	.EQU	H'08		; R	0:SW4  ON
;XPSW5:	.EQU	H'10		; R	0:SW5  ON
;XPSW6:	.EQU	H'20		; R	0:SW6  ON
;XPSW7:	.EQU	H'40		; R	0:SW7  ON
;XPSW8:	.EQU	H'80		; R	0:SW8  ON

SWPDBB:	.RES.B	  1		;OUT  LCD DATA
SWPDBC:	.RES.B	  1		;OUT  LCD CONTROL
XLCDRS:	.EQU	H'01		;R/W	0:INSTRUCTION	1:DATA
XLCDRW:	.EQU	H'02		;R/W	0:WRITE		1:READ
XLCDE:	.EQU	H'04		;R/W	0:DATA DISABLE	1:ENABLE
;	.EQU	H'08		;R/W	  NO FUNCTION
QLCDRS:	.EQU	  0		;
QLCDRW:	.EQU	  1		;
QLCDE:	.EQU	  2		;
				;IN   PANEL SW INPUT
XPSW12:	.EQU	H'10		; R 	0:SW12 ON
;	.EQU	H'20		; R 	  ALWAYS 1
;	.EQU	H'40		; R 	  ALWAYS 1
;	.EQU	H'80		; R 	  ALWAYS 1

SWPDBG:	.RES.B	  1		;IN   SW INPUT
XPSW9:	.EQU	H'01		; R	0:SW9  ON
XPSW10:	.EQU	H'02		; R	0:SW10 ON
XPSW11:	.EQU	H'04		; R	0:SW11 ON
XCVRS:	.EQU	H'08		; R	1:COVER OPEN
QCVRS:	.EQU	  3		;

SWPDBE:	.RES.B	  1		;OUT  LED OUTPUT
;XLED1:	.EQU	H'01		;R/W	0:LED1 ON
;XLED2:	.EQU	H'02		;R/W	0:LED2 ON
;XLED3:	.EQU	H'04		;R/W	0:LED3 ON
;XLED4:	.EQU	H'08		;R/W	0:LED4 ON
;XLED5:	.EQU	H'10		;R/W	0:LED5 ON
;XLED6:	.EQU	H'20		;R/W	0:LED6 ON
;XLED7:	.EQU	H'40		;R/W	0:LED7 ON
;XLED8:	.EQU	H'80		;R/W	0:LED8 ON

SWPDBF:	.RES.B	  1		;OUT  LCD CONTRAST
;	.EQU	H'01		;R/W	  LCD CONTRAST ADJUST 0
;	.EQU	H'02		;R/W	  LCD CONTRAST ADJUST 1
;	.EQU	H'04		;R/W	  LCD CONTRAST ADJUST 2
;	.EQU	H'08		;R/W	  LCD CONTRAST ADJUST 3
;XLED9:	.EQU	H'10		;R/W	0:LED9 ON
;	.EQU	H'20		;R/W	  NO FUNCTION
;	.EQU	H'40		;R/W	  NO FUNCTION
;	.EQU	H'80		;R/W	  NO FUNCTION
ZLCDAJ:	.EQU	H'0F		;	  LCD CONTRAST ADJUST MASK
QLED9:	.EQU	  4		;

	.RES.B	  1		;     NO FUNCTION
SWPCNT:	.RES.B	  1		;OUT  SW PANEL LSI CONTROL WORD
ZWRMD1:	.EQU	H'8A		; W	PE:E, PF:E, PA:IN, PB,OUT PC:IN/OUT
ZRDMD1:	.EQU	H'8E		; W	PE:E, PF:E, PA:IN, PB,IN  PC:IN/OUT
ZWRMD2:	.EQU	H'88		; W	PE:E, PF:E, PA:IN, PB,OUT PC:OUT
ZRDMD2:	.EQU	H'8C		; W	PE:E, PF:E, PA:IN, PB,IN  PC:OUT
	.LIST	ON
