PRE8 AX_ANK.MAR/NOLIST
ASM8 AX_ANK.SRC/NOLIST=AX_ANK.ERR
DEL AX_ANK.SRC

PRE8 AX_BCD.MAR/NOLIST
ASM8 AX_BCD.SRC/NOLIST=AX_BCD.ERR
DEL AX_BCD.SRC

PRE8 AX_DP1.MAR/NOLIST
ASM8 AX_DP1.SRC/NOLIST=AX_DP1.ERR
DEL AX_DP1.SRC

PRE8 AX_DP2.MAR/NOLIST
ASM8 AX_DP2.SRC/NOLIST=AX_DP2.ERR
DEL AX_DP2.SRC

PRE8 AX_DLD.MAR/NOLIST
ASM8 AX_DLD.SRC/NOLIST=AX_DLD.ERR
DEL AX_DLD.SRC

PRE8 AX_DP3.MAR/NOLIST
ASM8 AX_DP3.SRC/NOLIST=AX_DP3.ERR
DEL AX_DP3.SRC

PRE8 AX_DP3L.MAR/NOLIST
ASM8 AX_DP3L.SRC/NOLIST=AX_DP3L.ERR
DEL AX_DP3L.SRC

PRE8 AX_EDT.MAR/NOLIST
ASM8 AX_EDT.SRC/NOLIST=AX_EDT.ERR
DEL AX_EDT.SRC

PRE8 AX_ESC.MAR/NOLIST
ASM8 AX_ESC.SRC/NOLIST=AX_ESC.ERR
DEL AX_ESC.SRC

PRE8 AX_IMG.MAR/NOLIST
ASM8 AX_IMG.SRC/NOLIST=AX_IMG.ERR
DEL AX_IMG.SRC

PRE8 AX_IOS.MAR/NOLIST
ASM8 AX_IOS.SRC/NOLIST=AX_IOS.ERR
DEL AX_IOS.SRC

PRE8 AX_KNJ.MAR/NOLIST
ASM8 AX_KNJ.SRC/NOLIST=AX_KNJ.ERR
DEL AX_KNJ.SRC

PRE8 AX_MON.MAR/NOLIST
ASM8 AX_MON.SRC/NOLIST=AX_MON.ERR
DEL AX_MON.SRC

PRE8 AX_JST.MAR/NOLIST
ASM8 AX_JST.SRC/NOLIST=AX_JST.ERR
DEL AX_JST.SRC

PRE8 AX_TB1.MAR/NOLIST
ASM8 AX_TB1.SRC/NOLIST=AX_TB1.ERR
DEL AX_TB1.SRC

PRE8 AX_MSG.MAR/NOLIST
ASM8 AX_MSG.SRC/NOLIST=AX_MSG.ERR
DEL AX_MSG.SRC

PRE8 AX_SUB.MAR/NOLIST
ASM8 AX_SUB.SRC/NOLIST=AX_SUB.ERR
DEL AX_SUB.SRC

PRE8 AX_PRT.MAR/NOLIST
ASM8 AX_PRT.SRC/NOLIST=AX_PRT.ERR
DEL AX_PRT.SRC

PRE8 AX_SWS.MAR/NOLIST
ASM8 AX_SWS.SRC/NOLIST=AX_SWS.ERR
DEL AX_SWS.SRC

PRE8 AX_SVT.MAR/NOLIST
ASM8 AX_SVT.SRC/NOLIST=AX_SVT.ERR
DEL AX_SVT.SRC

PRE8 AX_SWP.MAR/NOLIST
ASM8 AX_SWP.SRC/NOLIST=AX_SWP.ERR
DEL AX_SWP.SRC

PRE8 AX_TB2.MAR/NOLIST
ASM8 AX_TB2.SRC/NOLIST=AX_TB2.ERR
DEL AX_TB2.SRC

PRE8 AX_EXPM.MAR/NOLIST
ASM8 AX_EXPM.SRC/NOLIST=AX_EXPM.ERR
DEL AX_EXPM.SRC

PRE8 EEPIOS.MAR/NOLIST
ASM8 EEPIOS.SRC/NOLIST=EEPIOS.ERR
DEL EEPIOS.SRC

PRE8 PNLIOS.MAR/NOLIST
ASM8 PNLIOS.SRC/NOLIST=PNLIOS.ERR
DEL PNLIOS.SRC

PRE8 SYSDP3.MAR/NOLIST
ASM8 SYSDP3.SRC/NOLIST=SYSDP3.ERR
DEL SYSDP3.SRC

PRE8 SYSDP3L.MAR/NOLIST
ASM8 SYSDP3L.SRC/NOLIST=SYSDP3L.ERR
DEL SYSDP3L.SRC

PRE8 SYSINI.MAR/NOLIST
ASM8 SYSINI.SRC/NOLIST=SYSINI.ERR
DEL SYSINI.SRC

PRE8 SYSLIB.MAR/NOLIST
ASM8 SYSLIB.SRC/NOLIST=SYSLIB.ERR
DEL SYSLIB.SRC

PRE8 SYSIOS.MAR/NOLIST
ASM8 SYSIOS.SRC/NOLIST=SYSIOS.ERR
DEL SYSIOS.SRC

PRE8 SYSPRT.MAR/NOLIST
ASM8 SYSPRT.SRC/NOLIST=SYSPRT.ERR
DEL SYSPRT.SRC

PRE8 ksctbl.MAR/NOLIST
ASM8 ksctbl.SRC/NOLIST=ksctbl.ERR
DEL ksctbl.SRC

PRE8 NDRFNT.MAR/NOLIST
ASM8 NDRFNT.SRC/NOLIST=NDRFNT.ERR
DEL NDRFNT.SRC

PRE8 NLQFNT.MAR/NOLIST
ASM8 NLQFNT.SRC/NOLIST=NLQFNT.ERR
DEL NLQFNT.SRC


ASM8 AX_MAP.SRC/NOLIST=AX_MAP.ERR

ASM8 AX_OCR.SRC/NOLIST=AX_OCR.ERR

ASM8 H8RTMB0.SRC/NOLIST=H8RTMB0.ERR

ASM8 H8RTMS0.SRC/NOLIST=H8RTMS0.ERR

ASM8 H8RTMM0.SRC/NOLIST=H8RTMM0.ERR

ASM8 SYSMAP.SRC/NOLIST=SYSMAP.ERR

ASM8 M43RTM.SRC/NOLIST=M43RTM.ERR

ASM8 M43RTMP.SRC/NOLIST=M43RTMP.ERR

ASM8 M43RTMT.SRC/NOLIST=M43RTMT.ERR

ASM8 SYSTBL.SRC/NOLIST=SYSTBL.ERR

LNK /SUBCOMMAND=AX_DP21.SUB
LNK /SUBCOMMAND=AX_DP2.SUB
LNK /SUBCOMMAND=M43RTM.SUB
LNK /SUBCOMMAND=M4324SYS.SUB
LNK /SUBCOMMAND=AX_SYS.SUB
LNK /SUBCOMMAND=M4324AX.SUB
CNVS M4324AX.ABS M4324AX.HEX
HEXBIN2 M4324AX.HEX M4324AX.AB
