	.LIST	OFF
;********************************************************
;							*
;	M4324 OPERATION PANEL I/O SYSTEM DEFINITION	*
;							*
;	FILE NAME	PNLIOS.H			*
;	CREATED		 7/DEC/1990			*
;							*
;********************************************************
;
;	OPERATION PANEL I/O CALL ENTRY
;
	.IMPORT		LCDCAL	; LCD I/O SYSTEM CALL ENTRY
	.IMPORT		SWPDI	; PANEL SW PROCESS DISABLE
	.IMPORT		SWPEN	; PANEL SW PROCESS ENABLE
	.IMPORT		SWPT1S	; SELECT PANEL SW TABLE 1
	.IMPORT		SWPT2S	; SELECT PANEL SW TABLE 2
	.IMPORT		LCDDLD	; OUTPUT LCD DOWN LOAD CG
	.IMPORT		LCDCON	; SET LCD CONTRAST
	.IMPORT		LCDBFS	; SELECT LCD BUFFER
	.IMPORT		LCDBLS	; SET DISPLAY BLINK
	.IMPORT		LCDBLC	; CLEAR DISPLAY BLINK
	.IMPORT		LCDS1	; DISPLAY STRING FROM 1ST LINE
	.IMPORT		LCDS2	; DISPLAY STRING FROM 2ND LINE
	.IMPORT		LCDLST	; DISPLAY STRING LIST
	.IMPORT		LCDLX	; DISPLAY STRING LIST
	.IMPORT		LCDSX	; DISPLAY STRING FROM R2 POSITION
	.IMPORT		LCDSTR	; DISPLAY STRING
	.IMPORT		LCDCX	; DISPLAY CHARACTER
	.IMPORT		LCDCHR	; DISPLAY CHARACTER
	.IMPORT		LCDHX1	; DISPLAY 1 DIGIT HEX CHARCTER
	.IMPORT		LCDHX2	; DISPLAY 2 DIGIT HEX CHARCTER
	.IMPORT		LCDHX3	; DISPLAY 3 DIGIT HEX CHARCTER
	.IMPORT		LCDHX4	; DISPLAY 4 DIGIT HEX CHARCTER
	.IMPORT		LCDDE0	; DISPLAY DECIMAL CHARCTER
	.IMPORT		LCDDEC	; DISPLAY DECIMAL CHARCTER (LEADING 0 SUPPRESS)
	.IMPORT		BZOFF	; BUZZER OFF
	.IMPORT		BZOFF1	; BUZZER OFF 1
	.IMPORT		BZON1	; BUZZER SINGLE SHOT ON 1
	.IMPORT		BZON2	; BUZZER SINGLE SHOT ON 2
	.IMPORT		BZCON1	; BUZZER CONTINUOUS ON 1
	.IMPORT		BZCON2	; BUZZER CONTINUOUS ON 2
	.IMPORT		BZINT1	; BUZZER INTERMITTENT ON 1
	.IMPORT		BZINT2	; BUZZER INTERMITTENT ON 2
	.IMPORT		LEDOFF	; OFF LED STATUS
	.IMPORT		LEDON	; ON  LED STATUS
	.IMPORT		LEDXOR	; XOR LED STATUS
	.IMPORT		LEDSET	; SET LED STATUS
	.IMPORT		LEDBLS	; SET LED BLINK
	.IMPORT		LEDBLC	; CLEAR LED BLINK
;
;	TIMER INTERVAL
;
ZTI2:	.EQU	   25		;  25mS	INTPNL INTERRUPT INTERVAL
;
;	LCD FUNCTION CODE
;
;	.EQU	  0		; END OF STRING
ZLOF:	.EQU	  1		; DISPLAY OFF
ZLON0:	.EQU	  2		; DISPLAY ON (CURSOR OFF)
ZLON1:	.EQU	  3		; DISPALY ON (UNDERLINE CURSOR)
ZLON2:	.EQU	  4		; DISPLAY ON (BLINK CURSOR)
ZLCL0:	.EQU	  5		; DISPLAY ALL CLEAR AND CURSOR HOME
ZLCL1:	.EQU	  6		; DISPLAY CLEAR TO END OF DISPLAY
;	.EQU	  7		; NO FUNCTION
ZLDL1:	.EQU	  8		; DOWN LOAD CHARACTER 1
ZLDL2:	.EQU	  9		; DOWN LOAD CHARACTER 2
ZLDL3:	.EQU	 10		; DOWN LOAD CHARACTER 3
ZLDL4:	.EQU	 11		; DOWN LOAD CHARACTER 4
ZLDL5:	.EQU	 12		; DOWN LOAD CHARACTER 5
ZLDL6:	.EQU	 13		; DOWN LOAD CHARACTER 6
ZLDL7:	.EQU	 14		; DOWN LOAD CHARACTER 7
ZLDL8:	.EQU	 15		; DOWN LOAD CHARACTER 8
ZLPOS:	.EQU	128		; CURSOR POSITION SET
ZLCDSZ:	.EQU	 16		; LCD SIZE PER LINE
;
;	LED I/O MACRO
;
	.MACRO	LEDON	L
	BCLR.B	\L,@LEDF:8
	.ENDM

	.MACRO	LEDOFF	L
	BSET.B	\L,@LEDF:8
	.ENDM

	.MACRO	LEDNOT	L
	BNOT.B	\L,@LEDF:8
	.ENDM

	.MACRO	LEDSET	L
	MOV.B	\L,@LEDF:8
	.ENDM

	.MACRO	LEDCHK	L
	BTST.B	\L,@LEDF:8
	.ENDM

	.MACRO	LED9ON
	BCLR.B	#QLED9,@SWPDBF
	.ENDM

	.MACRO	LED9OF
	BSET.B	#QLED9,@SWPDBF
	.ENDM
	.LIST	ON
