	.LIST	OFF
	.SECTION	PNLRAM,DUMMY,LOCATE=H'0000
;********************************************************
;							*
;	M4324 OPERATION PANEL I/O RAM DEFINITION	*
;							*
;	FILE NAME	PNLRAM.H			*
;	CREATED		20/OCT/1990			*
;							*
;********************************************************
;
;	BUZZER TIMER
;
	.IMPORT	BUZT
	.ORG	  0
YBZT1:	.RES.W	  1		; BUZZER ON  TIMER COUNTER
YBZT2:	.RES.W	  1		; BUZZER OFF TIMER COUNTER
YBZC:	.RES.W	  1		; BUZZER INT. ON/OFF COUNTER
YBZTS1:	.RES.W	  1		; BUZZER INT. ON  TIME SAVE
YBZTS2:	.RES.W	  1		; BUZZER INT. OFF TIME SAVE
;
;	LED BLINK TIMER
;
	.IMPORT	LEDT
	.ORG	  0
YLEDT:	.RES.B	  1		; LED BLINK TIMER COUNTER
YLEDTS:	.RES.B	  1		; LED BLINK INTERVAL TIME SAVE
YLEDS:	.RES.B	  1		; LED BLINK STATUS SAVE
YLEDSZ:				; LED BLINK TIMER SIZE
ZLEDTC:	.EQU	  2		; NO. OF LED BLINK TIMER
;
;	LCD BUFFER
;
	.IMPORT	LCDBF1
	.IMPORT	LCDBF2
YLCDS1:	.EQU	 -6		; LCD BLINK STATUS SAVE 1
YLCDS2:	.EQU	 -4		; LCD BLINK STATUS SAVE 2
YLCDPC:	.EQU	 -2		; LCD DISPLAY POSITION COUNTER
YLCDMD:	.EQU	 -1		; LCD DISPLAY MODE SAVE
ZLCOF	.EQU	H'08		;   DISPLAY OFF
ZLCON0:	.EQU	H'0C		;   DISPLAY ON (CURSOR OFF)
ZLCON1:	.EQU	ZLCON0+H'02	;   DISPLAY ON (UNDERLINE CURSOR)
ZLCON2:	.EQU	ZLCON0+H'01	;   DISPLAY ON (BLINK CURSOR)
	.LIST	ON
