	.LIST	OFF
	.SECTION	SLVRAM,DUMMY,LOCATE=H'0000
;********************************************************
;							*
;	M4324 SLAVE CPU RAM MAP DEFINITION		*
;							*
;	FILE NAME	SLVRAM.H			*
;	CREATED		18/MAR/1991			*
;							*
;********************************************************
;
;	SLAVE CPU RAM ADDRESS MAP
;
	.RES.B	 46		; CR MOTOR PARAMETER
	.RES.B	 18		;
LFINLK:	.RES.B	 51		; LF MOTOR PARAMETER
ADTOPV:	.RES.B	  1		; TOP SENSOR THRESHOLD
PECNST:	.RES.B	  6		; PE CHECK COUNT
	.RES.B	 22		;
RSSPD:	.RES.B	  1		; RIBBON SHIFT SPEED
	.RES.B	 15		;
CLM10D:	.RES.B	 14		; PRINT COLUMN ADJUST VALUE
CLMEND:	.RES.B	 24		;

SPECF:	.RES.B	  1		; SPECIFICATION FLAG
;QLF12:	.EQU	  0		;   1:LF 1-2 PAHSE
;	.EQU	  1		;
;	.EQU	  2		;
;	.EQU	  3		;
;	.EQU	  4		;
;	.EQU	  5		;
;	.EQU	  6		;
QSIPTE	.EQU	  7		;   1:INITIAL PARAMETER TRANSMIT END
XLF12:	.EQU	H'01		;

CANCMD:	.RES.B	  1		; CANCEL FLAG
XCANCM:	.EQU	H'01		;   1:COMMAND CANCEL
XSTOPE:	.EQU	H'02		;   1:STOP FORMS ESCAPE FEDD

PRNSF:	.RES.B	  1		; SENSOR STATUS
;QSPES:	.EQU	  0		;   1:SHEET NOT PE	0:PE
;QFPES:	.EQU	  1		;   1:FORMS NOT PE	0:PE
;QBPES:	.EQU	  2		;   1:BOTTOM NOT PE	0:PE
;QLVRS:	.EQU	  3		;   1:SHEET		0:FORMS
;	.EQU	  4		;     NO FUNCTION
;	.EQU	  5		;     NO FUNCTION
;	.EQU	  6		;     NO FUNCTION
;	.EQU	  7		;     NO FUNCTION

ERRF0:	.RES.B	  1		; ERROR 0 STATUS
QESPD:	.EQU	  0		;   1:CR SPEED ERROR
QEDRV:	.EQU	  1		;   1:CR/LF MOTOR DRIVER ERROR
QETR:	.EQU	  2		;   1:STEP MOTOR DRIVER ERROR
QEHD:	.EQU	  3		;   1:HEAD DRIVER ERROR
QEFRM:	.EQU	  4		;   1:FRAME ERROR
QECREC:	.EQU	  5		;   1:CR ENCODER ERROR
;	.EQU	  6		;     NO FUNCTION
;	.EQU	  7		;     NO FUNCTION

ERRF1:	.RES.B	  1		; ERROR 1 STATUS
QEHSEC:	.EQU	  0		;   1:HEAD SHIFT ENCODER ERROR
QEHDS:	.EQU	  1		;   1:HEAD SHIFT ERROR
QERBS:	.EQU	  2		;   1:RIBBON SHIFT ERROR
QELVR:	.EQU	  3		;   1:LEVER CHANGE ERROR
QEINEJ:	.EQU	  4		;   1:INSERT/EJECT ERROR
;	.EQU	  5		;     NO FUNCTION
;	.EQU	  6		;     NO FUNCTION
;	.EQU	  7		;     NO FUNCTION
	.PAGE
PSPH:	.RES.B	  1		; HEAD SHIFT MOTOR PHASE STATUS
PSADRS:	.RES.W	  1		; HEAD SHIFT MOTOR ADDRESS STATUS
PSSTF:	.RES.B	  1		; HEAD SHIFT MANUAL MOVE STATUS
;QPSMV:	.EQU	  0		;   1:MANUAL MOVE
;	.EQU	  1		;     NO FUNCTION
;	.EQU	  2		;     NO FUNCTION
;	.EQU	  3		;     NO FUNCTION
;	.EQU	  4		;     NO FUNCTION
;	.EQU	  5		;     NO FUNCTION
;	.EQU	  6		;     NO FUNCTION
;	.EQU	  7		;     NO FUNCTION

SEQNO:	.RES.B	  1		; ABORT COMMAND SEQUENCE NO. STATUS
;	.EQU	  0		;     SEQUENCE NO. BIT 0
;	.EQU	  1		;     SEQUENCE NO. BIT 1
;	.EQU	  2		;     NO FUNCTION
;	.EQU	  3		;     NO FUNCTION
;	.EQU	  4		;     NO FUNCTION
;	.EQU	  5		;     NO FUNCTION
;	.EQU	  6		;     NO FUNCTION
;	.EQU	  7		;     NO FUNCTION

PRDIR:	.RES.B	  1		; PRINT DIRECTION STATUS
;QPRFWD:.EQU	  0		;   1:FORWARD PRINT	0:REVERSE PRINT
;	.EQU	  1		;     NO FUNCTION
;	.EQU	  2		;     NO FUNCTION
;	.EQU	  3		;     NO FUNCTION
;	.EQU	  4		;     NO FUNCTION
;	.EQU	  5		;     NO FUNCTION
;	.EQU	  6		;     NO FUNCTION
;	.EQU	  7		;     NO FUNCTION

	.RES.B	  1		; NOT USED
CSTOPC:	.RES.W	  1		; SHEET  OVER PE COUNTER STATUS
JNLOPC:	.RES.W	  1		; FORMS  OVER PE COUNTER STATUS
BTMOPC:	.RES.W	  1		; BOTTOM OVER PE COUNTER STATUS
ADTOPS:	.RES.B	  1		; TOP SENSOR A/D PORT STATUS
	.RES.B	  3		; NOT USED
TMRCTF:	.RES.B	  1		; SLAVE CPU RUN STATUS
	.RES.B	 32		; NOT USED
SLREV0:	.RES.B	  1		; SLAVE CPU REVISION NO. STATUS 0
SLREV1:	.RES.B	  1		; SLAVE CPU REVISION NO. STATUS 1
SLREV2:	.RES.B	  1		; SLAVE CPU REVISION NO. STATUS 2
	.LIST	ON
