	.LIST	OFF
;********************************************************
;							*
;	M4324 EEPROM SYSTEM PART MAP DEFINITION		*
;							*
;	FILE NAME	SYSEEP.H			*
;	CREATED		12/FEB/1990			*
;							*
;********************************************************
;
	.IMPORT		EEPBF	; EEPORM BUFFER 1

	.SECTION	EEPROM,DUMMY,LOCATE=H'0000
;
;	EEPROM SYSTEM DATA
;
E2ALM:	.RES.W	  1		; 00  ALARM ERROR CODE
E2ID:	.RES.W	  1		; 01  ID CODE
E2CUT:	.RES.W	  1		; 02  PAPER CUTTER DISTANCE
E2INF:	.RES.W	  1		; 03  FORMS  INSERT DISTANCE
E2INB:	.RES.W	  1		; 04  BOTTOM INSERT DISTANCE
E2INS0:	.RES.W	  1		; 05  SHEET  INSERT DISTANCE
E2INS1:	.RES.W	  1		; 06  SHEET  INSERT DISTANCE AT 3 BIN ACSF
E2INA0:	.RES.W	  1		; 07  ACSF0  INSERT DISTANCE
E2INA1:	.RES.W	  1		; 08  ACSF1  INSERT DISTANCE
E2INA2:	.RES.W	  1		; 09  ACSF2  INSERT DISTANCE
E2INA3:	.RES.W	  1		; 0A  ACSF3  INSERT DISTANCE
E2OPCS:	.RES.W	  1		; 0B  SHEET  PE DISTANCE
E2OPCF:	.RES.W	  1		; 0C  FORMS  PE DISTANCE
E2OPCB:	.RES.W	  1		; 0D  BOTTOM PE DISATNCE
E2CRHS:	.RES.W	  1		; 0E  CR POSITION OF HEAD SHIFT
E2RBSA:	.RES.W	  1		; 0F  RIBBON SHIFT ADJUST VALUE
E2HSL:	.RES.W	  1		; 10  HEAD SHIFT L
E2HSM1:	.RES.W	  1		; 11  HEAD SHIFT M1
E2HSN:	.RES.W	  1		; 12  HEAD SHIFT N
E2HSF:	.RES.W	  1		; 13  HEAD SHIFT MOTOR PHASE AT M1
E2PRSP:	.RES.W	  1		; 14  PRINT START POSITION
E2PRA1:	.RES.B	  1		; 15  PRINT REVERSE ADJUST FOR  1.0D
	.RES.B	  1		;				1.0C
	.RES.B	  1		; 16				1.0B
	.RES.B	  1		;				1.0A
	.RES.B	  1		; 17				1.5
	.RES.B	  1		;				2.0
	.RES.B	  1		; 18				3.0
E2PRA2:	.RES.B	  1		;     PRINT POSITION ADJUST FOR 1.0D
	.RES.B	  1		; 19				1.0C
	.RES.B	  1		;				1.0B
	.RES.B	  1		; 1A				1.0A
	.RES.B	  1		;				1.5
	.RES.B	  1		; 1B				2.0
	.RES.B	  1		;				3.0
E2ADV:	.RES.W	  1		; 1C  TOP SENSOR A/D PORT THRESHOLD
	.RES.W	  2		; 1D  RESERVED AREA
	.RES.W	  1		; 1F  CHECK SUM
	.LIST	ON
