	.LIST	OFF
;********************************************************
;							*
;	M4324 I/O SYSTEM DEFINITION			*
;							*
;	FILE NAME	SYSIOS.H			*
;	CREATED		19/OCT/1990			*
;							*
;********************************************************
	.SECTION	IOSTMR,DUMMY,LOCATE=H'0
;
;	BUZZER TIMER
;
	.ORG	  0
YBZT1:	.RES.W	  1		;   BUZZER ON  TIMER COUNTER
YBZT2:	.RES.W	  1		;   BUZZER OFF TIMER COUNTER
YBZC:	.RES.W	  1		;   BUZZER INT. ON/OFF COUNTER
YBZTS1:	.RES.W	  1		;   BUZZER INT. ON  TIME SAVE
YBZTS2:	.RES.W	  1		;   BUZZER INT. OFF TIME SAVE
;
;	LED BLINK TIMER
;
	.ORG	  0
YLEDT:	.RES.B	  1		;   LED BLINK TIMER COUNTER
YLEDTS:	.RES.B	  1		;   LED BLINK INTERVAL TIME SAVE
YLEDS:	.RES.B	  1		;   LED BLINK STATUS SAVE
YLEDSZ:				;   LED BLINK TIMER SIZE
ZLEDTC:	.EQU	  2		; NO. OF LED BLINK TIMER
;
;	LCD BUFFER
;
YLCDS1:	.EQU	 -6		;   LCD BLINK STATUS SAVE 1
YLCDS2:	.EQU	 -4		;   LCD BLINK STATUS SAVE 2
YLCDPC:	.EQU	 -2		;   LCD DISPLAY POSITION COUNTER
YLCDMD:	.EQU	 -1		;   LCD DISPLAY MODE SAVE
	.LIST	ON
