	.LIST	OFF
;********************************************************
;							*
;	M4324 SYSTEM LIBRARY DEFINITION			*
;							*
;	FILE NAME	SYSLIB.H			*
;	CREATED		12/DEC/1990			*
;							*
;********************************************************
;
;	SYSTEM LIBRARY CALL ENTRY
;
	.IMPORT		CHKOCG	; CHECK OPTION CG
	.IMPORT		CHKSCG	; CHECK STANDARD CG
	.IMPORT		INIEX1	; INITIALIZE EXPAND RAM PAGE 1
	.IMPORT		INIEX2	; INITIALIZE EXPAND RAM PAGE 2
	.IMPORT		INIEX3	; INITIALIZE EXPAND RAM PAGE 3
	.IMPORT		INIEX4	; INITIALIZE EXPAND RAM PAGE 4
	.IMPORT		INIPBF	; INITIALIZE PRINT BUFFER RAM
	.IMPORT		INIRAM	; INITIALIZE EXTERNAL RAM
				;
	.IMPORT		CHKROM	; CHECK PROGRAM ROM
	.IMPORT		CHKCG	; CHECK KANJI CG ROM
	.IMPORT		CHKRAM	; CHECK EXTERNAL RAM
	.IMPORT		CLRBF	; CLEAR BUFFER
	.IMPORT		FILBF	; FILL BUFFER
	.IMPORT		CLRBFW	; CLEAR BUFFER BY WORD
	.IMPORT		FILBFW	; FILL BUFFER BY WORD
	.IMPORT		COPYBF	; COPY BUFFER

;
;	SYSTEM LIBRARY CALL MACRO
;
	.MACRO	CALSYS	E
\;	.AIF	"\E" EQ "R0"
\;	TRAPA	#8
\;	.EXITM
\;	.AENDI
	MOV.W	\E,R0
	TRAPA	#8
	.ENDM
	.LIST	ON
