	.LIST	OFF
;********************************************************
;							*
;	M4324 MONITOR TASK COMMON DEFINITION		*
;							*
;	FILE NAME	SYSMON.H			*
;	CREATED		19/SEP/1990			*
;							*
;********************************************************
;
;	EVENT FLAG
;
;FACTF:	.EQU	H'0001		; DP3 ACTION FINISH
FSALM:	.EQU	H'0002		; SET ALARM ERROR   MODE
FCCVR:	.EQU	H'0004		; CHECK COVER  STATUS
FCACF:	.EQU	H'0008		; CHECK ACSF   STATUS
FCOPC:	.EQU	H'0010		; CHECK OPC    STATUS
FCSNS:	.EQU	H'0020		; CHECK SENSOR STATUS
FSINE:	.EQU	H'0040		; SET INSERT ERROR
FSEJE:	.EQU	H'0080		; SET EJECT  ERROR
FSPRD:	.EQU	H'0100		; SET PRINT DISABLE MODE
FSPRE:	.EQU	H'0200		; SET PRINT ENABLE  MODE
FSPRO:	.EQU	H'0400		; SET PRINT ENABLE  MODE  (PE OVERRIDE ENABLE)
;
;	MONITOR CALL MACRO
;
	.MACRO	CALMON	F
	MOV:I	#\F,R2
	TRAPA	#10
	.ENDM
	.LIST	ON
