	.LIST	OFF
;********************************************************
;							*
;	M4324 PRINT SYSTEM DEFINITION			*
;							*
;	FILE NAME	SYSPRT.H			*
;	CREATED		20/DEC/1990			*
;							*
;********************************************************
;
	.SECTION	PRTRAM,DUMMY,LOCATE=H'0000
;
;	PRINT COMMAND BUFFER
;
	.ORG	  0
YPCF1:	.RES.B	  1		; PRINT OPTION FLAG 1
Q7PP:	.EQU	  0		;   1:COPY ENHANCE PRINT
QDBSP:	.EQU	  1		;   1:DOUBLE STRIKE PRINT
QPRSA:	.EQU	  2		;   1:PHYSICAL RIBBON ADDRESS
QPFMT:	.EQU	  3		;   1:PHYSICAL PRINT FORMAT
;	.EQU	  4		;
;QDOVR:	.EQU	  5		;   1:DUTY OVER PRINT
;QPBBS:	.EQU	  6		;   1:PRINT BUFFER RAM B SELECT
QPSNC:	.EQU	  7		;   1:PRINT SPEED NOT CHANGE

YPCF2:	.RES.B	  1		; PRINT OPTION FLAG 2
QRBSM:	.EQU	  0		;   1:MAGENTA COLOUR
QRBSC:	.EQU	  1		;   1:CYAN    COLOUR
QRBSY:	.EQU	  2		;   1:YELLOW  COLOUR
QRBSB:	.EQU	  3		;   1:BLACK   COLOUR
QPFWD:	.EQU	  4		;   1:FORWARD PRINT
QPREV:	.EQU	  5		;   1:REVERSE PRINT
QPSAM:	.EQU	  6		;   1:SAME DIRECTION PRINT
;	.EQU	  7  		;
XRBSM:	.EQU	H'01		;
XRBSC:	.EQU	H'02		;
XRBSY:	.EQU	H'04		;
XRBSB:	.EQU	H'08		;
XPFWD:	.EQU	H'10		;
XPREV:	.EQU	H'20		;
XPSAM:	.EQU	H'40		;

YPCDPI:	.RES.B	  1		; PRINT DPI FLAG
ZDP360:	.EQU	  0		;     360 DPI
ZDP240:	.EQU	  1		;     240 DPI
ZDP180:	.EQU	  2		;     180 DPI
ZDP120:	.EQU	  3		;     120 DPI
ZDPMSK:	.EQU	  3		;
QPSB:	.EQU	  5		;   1:PRINT SPEED B MODE
QPSC:	.EQU	  6		;   1:PRINT SPEED B MODE
QPSD:	.EQU	  7		;   1:PRINT SPEED B MODE

	.RES.B	  3		; PRINT USER AREA
YPCDOT:	.RES.W	  1		; PRINT DOT COUNT
YPCMAX:	.RES.W	  1		; MAX PRINT COLUMN SAVE
YPCBLP:	.RES.W	  1		; PRINT BUFFER LEFT  POINTER
YPCBRP:	.RES.W	  1		; PRINT BUFFER RIGHT POINTER
YPCPTP:	.RES.W	  1		; PRINT TIMER TABLE POINTER

YPCFMT:	.RES.B	  1		; CMDFMT
;	.EQU	0->1		;     SEQUENCE NO.
;QDATA:	.EQU	  2		;     ALWAYS 0
;QERCHK:.EQU	  3		;   1:NO PE CHECK
;	.EQU	  4		;     ALWAYS 0
;QPAMD1:.EQU	  5		;     PAPER MODE BIT 1
;QPAMD2:.EQU	  6		;     PAPER MODE BIT 2
;	.EQU	  7		;     ALWAYS 0

YPCCOF:	.RES.B	  1		; SLCOF
ZPBID:	.EQU	  1		;     BI DIRECTION PRINT
ZPFWD:	.EQU	  2		;     FORWARD PRINT
ZPREV:	.EQU	  3		;     REVERSE PRINT
ZPSAM:	.EQU	  4		;     SAME DIRECTION PRINT

YPCRSA:	.RES.B	  1		; RIBBON SHIFT ADDRESS
ZRBSB:	.EQU	  0		;     BLACK   COLOUR BAND NO.
ZRBSC:	.EQU	  1		;     CYAN    COLOUR BAND NO.
ZRBSM:	.EQU	  2		;     MAGENTA COLOUR BAND NO.
ZRBSY:	.EQU	  3		;     YELLOW  COLOUR BAND NO.
ZRBSR:	.EQU	  4		;     RED     COLOUR BAND NO.
ZRBSS:	.EQU	  5		;     BLACK   SHIFT  BAND NO.

YPCPIT	.RES.B	  1		; PRINT PITCH
;XDP360:.EQU	H'01		;     1/360 INCH
;XDP240:.EQU	H'02		;     1/240 INCH
;XDP180:.EQU	H'04		;     1/180 INCH
;XDP120:.EQU	H'08		;     1/120 INCH

YPCFC:	.RES.B	  1		; PRINT FIELD COUNT
ZPCFC:	.EQU	  5		;     MAX FIELD COUNT

YPCFLD:	.RES.B	  5*5		; PRINT FIELD
;
;	PRINT FIELD
;
	.ORG	  0
	.RES.B	  1		; PRINT SPEED
	.RES.B	  2		; LEFT  COLUMN
	.RES.B	  2		; RIGHT COLUMN
YPCSZ:				; 1 FIELD SIZE
;
;	PRINT SPEED BUFFER
;
ZPSFC:	.EQU	 10		; MAX FIELD COUNT
	.ORG	  0
YPSFLG:	.RES.B	  1		; END MARK FLAG
YPSSPD:	.RES.B	  1		; PRINT SPEED
YPSFLC:	.RES.W	  1		; LEFT  COLUMN
YPSFRC:	.RES.W	  1		; RIGHT COLUMN
YPSSZ:				; 1 FIELD SIZE
	.LIST	ON
