	.LIST		OFF
	.SECTION	SYSRAM,DUMMY,LOCATE=H'FEC0
;********************************************************
;							*
;	M4324 SYSTEM GLOBAL AREA DEFINITION		*
;							*
;	FILE NAME	SYSRAM.H			*
;	CREATED		18/JAN/1991			*
;							*
;********************************************************
;
SWSF:	.RES.W	  1		; PANEL SW STATUS
LEDF:	.RES.B	  1		; LED STATUS FLAG
PSWDF:	.RES.B	  1		; PANEL SW DISABLE FLAG
QDALM:	.EQU	  0		;   1:DISABLE BY ALARM ERROR
;	.EQU	  1		;   1:DISABLE BY USER DEFINE
;	.EQU	  2		;   1:DISABLE BY USER DEFINE
;	.EQU	  3		;   1:DISABLE BY USER DEFINE
;	.EQU	  4		;   1:DISABLE BY USER DEFINE
;	.EQU	  5		;   1:DISABLE BY USER DEFINE
;	.EQU	  6		;   1:DISABLE BY USER DEFINE
;	.EQU	  7		;   1:DISABLE BY USER DEFINE

PNLCF:	.RES.B	  1		; PANEL I/O CONTROL FLAG
QSWT2S:	.EQU	  0		;   1:PANEL SW TABLE 2 SELECT
QBZOF:	.EQU	  1		;   1:BUZZER OFF AT SW ON
QESCSS:	.EQU	  2		;   1:STOP FORMS ESCAPE AT SW ON
QESCSU:	.EQU	  3		;   1:STOP FORMS ESCAPE AT USER OPTION
;	.EQU	  4		;
;	.EQU	  5		;
;	.EQU	  6		;
;	.EQU	  7		;

OPTAF:	.RES.B	  1		; OPTION ATTACHEMENT STATUS FLAG
;	.EQU	  0		;     NO FUNCTION
;	.EQU	  1		;     NO FUNCTION
QLBUSY:	.EQU	  2		;   1:LINE BUSY MODE
QRBNS:	.EQU	  3		;   0:BLACK RIBBON
QSELA:	.EQU	  4		;     ASCF TYPE SELECT
QACSW:	.EQU	  5		;   0:ACSF ATTACHED
QMNSW:	.EQU	  6		;     ACSF MANUAL/AUTO SW
QPIFD:	.EQU	  7		;   0:PARALLEL I/F DETECT
XSELA:	.EQU	H'10		;
XACSW:	.EQU	H'20		;
XMNSW:	.EQU	H'40		;

PRLFF:	.RES.B	  1		; PRINT/LF STATUS FLAG
QPRFWD:	.EQU	  0		;   1:FORWARD PRINT
QPRACT:	.EQU	  1		;   1:PRINT ACTIVE
QIGOPC:	.EQU	  2		;   1:IGNORE OPC STATUS
QLFACT:	.EQU	  3		;   1:FEED ACTIVE
;	.EQU	  4		;
QCCAND:	.EQU	  5		;   1:COMMAND CANCEL DONE
QCCANE:	.EQU	  6		;   1:COMMAND CANCEL ENABLE
QCCANS:	.EQU	  7		;   1:COMMAND CANCEL SEND

PRBFF:	.RES.B	  1		; PRINT BUFFER FLAG
QPBDI:	.EQU	  0		;   1:PRINT BUFFER SELECT DISABLE
QPBEN:	.EQU	  1		;   1:PRINT BUFFER ENABLE
QPBAB:	.EQU	  2		;   1:PRINT BUFFER A BUSY
QPBBB:	.EQU	  3		;   1:PRINT BUFFER B BUSY
;	.EQU	  4		;
QDOVR:	.EQU	  5		;   1:DUTY OVER PRINT
QPBBS:	.EQU	  6		;   1:PRINT BUFFER B SELECT FOR LOAD
QPBBP:	.EQU	  7		;   1:PRINT BUFFER B PRINTED
XDOVR:	.EQU	H'20		;
XPBBS:	.EQU	H'40		;

SNSF:	.RES.B	  1		; SENSOR STATUS FLAG
QSPES:	.EQU	  0		;   1:SHEET NOT PE	0:PE
QFPES:	.EQU	  1		;   1:FORMS NOT PE	0:PE
QBPES:	.EQU	  2		;   1:BOTTOM NOT PE	0:PE
QLVRS:	.EQU	  3		;   1:SHEET		0:FORMS
;	.EQU	  4		;
;	.EQU	  5		;
;	.EQU	  6		;
;	.EQU	  7		;
XSPES:	.EQU	H'01		;
XFPES:	.EQU	H'02		;
XBPES:	.EQU	H'04		;

ERRSF:	.RES.B	  1		; ERROR STATUS FLAG
QERBW:	.EQU	  0		;   1:RIBBON WIND MOTOR ERROR DETECT
QHSER:	.EQU	  1		;   1:HEAD SHIFT MOTOR ERROR RETRY
QHSMV:	.EQU	  2		;   1:HEAD SHIFT MANUAL MOVE
QHDALM:	.EQU	  3		;   1:HEAD THERMAL ALARM MODE
QJAMI:	.EQU	  4		;   1:INSERT ERROR
QJAME:	.EQU	  5		;   1:EJECT ERROR
QJAM:	.EQU	  6		;   1:INSERT/EJECT ERROR
;	.EQU	  7		;

ADPS:	.RES.B	  1		; TOP SENSOR A/D PORT STATUS SAVE
HSPS:	.RES.B	  1		; HEAD SHIFT MOTOR PHASE SAVE
HSPC:	.RES.W	  1		; HEAD SHIFT POSITION COUNTER
SOPC:	.RES.W	  1		; OVER PE COUNTER FOR SHEET
FOPC:	.RES.W	  1		; OVER PE COUNTER FOR FORMS
BOPC:	.RES.W	  1		; OVER PE COUNTER FOR BOTTOM
	.LIST	ON
