#ifndef _OSD_TAB_H
#define _OSD_TAB_H

extern code unsigned short Palette1Bit[];
extern code unsigned short Palette2Bit[];
extern code unsigned short Palette4Bit[];
extern code unsigned char OneBitFont[];
extern code unsigned char OneBitIcon[];
extern code unsigned char TwoBitIcon[];
extern code unsigned char OneBitFont2[];
extern code unsigned char OneBitFontPY[];
extern code unsigned char OneBitFontCH2[];
extern code unsigned char OneBitFontCH3[];
extern code unsigned char OneBitFontJP[];
extern code unsigned char OneBitFontJP2[];
extern code unsigned char TwoBitFont[];
extern code unsigned char TwoBitFont2[];
extern code unsigned char FourBitFont[];

extern unsigned char code DVI_EDID[];

/*
extern code unsigned char *DescTab[][9];
extern code ICONDEF MenuItem[7];
extern code unsigned char SPACE[];
extern code unsigned char *Tab_Color[];
extern code unsigned char *Tab_RGB[];
//extern code ICONDEF DsubMenuItem[17];
//extern code ICONDEF DviMenuItem[17];
//extern code ICONDEF VideoMenuItem[17];

extern code Byte RGBmenuItem[];
extern code Byte FactmenuItem[];
//extern code unsigned char LanguageDummy[];
extern code unsigned char *FuncTab[6];
extern Byte code Page0Item[7];
extern Byte code Page0ItemD[3];
extern Byte code Page0ItemY[5];
extern Byte code Page0ItemV[5];
extern Byte code Page1Item[2];
extern Byte code Page2Item[4];
extern Byte code Page3Item[1];
extern Byte code Page4Item[6];
extern Byte code Page5Item[5];
extern Byte code Page6Item[7];
extern code FACTDEF FactItem[26];

extern code unsigned char *UserTab[];
extern code unsigned char *KeyStrTab[];
extern code unsigned char *TurboStrTab[];
*/

#endif
